Repository STEllAR-GROUP/phylanx, pull requests merged in 2018-07, with the labels that each got.

#503 Making sure zero-dimensional numpy arrays are transferred properly from Python to C++
  python/src/bindings/type_casters.hpp
  tests/regressions/python/CMakeLists.txt
  tests/regressions/python/zero_dimensional_array_502.py
Labels: category: @Phylanx, type: enhancement

#514 Fix Remote Execution of PhySL
  cmake/Phylanx_SetupTarget.cmake
  phylanx/execution_tree/primitives/primitive_component_base.hpp
  phylanx/util/serialization/ast.hpp
  python/src/bindings/util.cpp
  src/execution_tree/primitives/primitive_component_base.cpp
  src/ir/node_data.cpp
  src/util/serialization/ast.cpp
  tests/unit/CMakeLists.txt
  tests/unit/distributed/CMakeLists.txt
  tests/unit/distributed/remote_run.cpp
Labels: submodule: backend, type: enhancement

#520 Add more options to the interpreter
  examples/interpreter/physl.cpp
Labels: type: enhancement

#519 Change Phylanx to build according to the pull request #3374 in HPX
  cmake/Phylanx_SetupTarget.cmake
  phylanx/config.hpp
Labels: category: CMake, type: compatibility issue

#521 Print HPX GIT commit hash during configuration
  cmake/Phylanx_SetupHPX.cmake
Labels: category: CMake, type: enhancement

#517 Moving SIMD structs for arithmetic operations to util
  phylanx/util/detail/add_simd.hpp
  phylanx/util/detail/div_simd.hpp
  phylanx/util/detail/mul_simd.hpp
  phylanx/util/detail/sub_simd.hpp
  src/plugins/arithmetics/add_operation.cpp
  src/plugins/arithmetics/div_operation.cpp
  src/plugins/arithmetics/mul_operation.cpp
  src/plugins/arithmetics/sub_operation.cpp
Labels: category: primitives, type: enhancement

#526 Fixing sum
  python/phylanx/ast/transformation.py
  tests/regressions/python/CMakeLists.txt
  tests/regressions/python/np_sum_489.py
Labels: category: @Phylanx, type: compatibility issue, type: enhancement

#525 Fixing list slicing to properly handle [::-1]
  src/plugins/matrixops/slicing_operation.cpp
  tests/regressions/python/CMakeLists.txt
  tests/regressions/python/list_iteration_524.py
Labels: category: primitives, type: compatibility issue, type: enhancement

#532 Fixing more tests that were broken as a result of merging recent compile API changes
  tests/regressions/execution_tree/shape_2nd_argument_406.cpp
  tests/regressions/execution_tree/slicing_nil_358.cpp
  tests/unit/plugins/arithmetics/add_lists.cpp
  tests/unit/plugins/controls/filter_operation.cpp
  tests/unit/plugins/controls/fold_left_operation.cpp
  tests/unit/plugins/controls/fold_right_operation.cpp
  tests/unit/plugins/controls/map_operation.cpp
  tests/unit/plugins/controls/parallel_map_operation.cpp
  tests/unit/plugins/controls/range_operation.cpp
  tests/unit/plugins/listops/car_cdr_operation.cpp
  tests/unit/plugins/listops/len_operation.cpp
  tests/unit/plugins/matrixops/list_slicing_operation.cpp
  tests/unit/plugins/matrixops/row_slicing.cpp
  tests/unit/plugins/matrixops/slicing_operation.cpp
  tests/unit/plugins/solvers/linear_solver.cpp
Labels: category: PhySL, type: enhancement

#535 Fixing format_string() primitive
  src/execution_tree/primitives/format_string.cpp
Labels: category: primitives, type: enhancement

#534 Move the functionality of the set primitive to the store primitive
  phylanx/execution_tree/primitives/access_variable.hpp
  phylanx/execution_tree/primitives/base_primitive.hpp
  phylanx/execution_tree/primitives/primitive_component.hpp
  phylanx/execution_tree/primitives/primitive_component_base.hpp
  phylanx/execution_tree/primitives/store_operation.hpp
  phylanx/execution_tree/primitives/variable.hpp
  phylanx/util/slicing_helpers.hpp
  src/execution_tree/primitives/access_variable.cpp
  src/execution_tree/primitives/base_primitive.cpp
  src/execution_tree/primitives/primitive_component.cpp
  src/execution_tree/primitives/primitive_component_base.cpp
  src/execution_tree/primitives/store_operation.cpp
  src/execution_tree/primitives/variable.cpp
  src/util/slicing_helpers.cpp
  tests/unit/execution_tree/primitives/store_operation.cpp
Labels: category: PhySL, category: primitives, type: enhancement

#536 adding append function to the list
  phylanx/plugins/listops/append_operation.hpp
  phylanx/plugins/listops/listops.hpp
  src/plugins/listops/append_operation.cpp
  src/plugins/listops/listops.cpp
  tests/unit/plugins/listops/CMakeLists.txt
  tests/unit/plugins/listops/append_operation.cpp
Labels: category: primitives, type: enhancement
