Repository STEllAR-GROUP/phylanx, pull requests merged in 2018-06, with the labels that each got.

#477 Remove redundant slicing primitives
  phylanx/plugins/matrixops/column_slicing.hpp
  phylanx/plugins/matrixops/matrixops.hpp
  phylanx/plugins/matrixops/row_slicing.hpp
  phylanx/plugins/matrixops/slicing_operation.hpp
  src/plugins/matrixops/column_slicing.cpp
  src/plugins/matrixops/matrixops.cpp
  src/plugins/matrixops/row_slicing.cpp
  src/plugins/matrixops/slicing_operation.cpp
Labels: category: primitives, submodule: backend, type: enhancement

#473 Fix AGAS names generated by compiler
  examples/interpreter/physl.cpp
  phylanx/execution_tree/compile.hpp
  phylanx/execution_tree/compiler/compiler.hpp
  phylanx/execution_tree/compiler/primitive_name.hpp
  src/execution_tree/compile.cpp
  src/execution_tree/compiler/compiler.cpp
  src/execution_tree/compiler/primitive_name.cpp
  src/execution_tree/primitives/base_primitive.cpp
  src/execution_tree/primitives/define_variable.cpp
  src/plugins/listops/car_cdr_operation.cpp
  src/plugins/matrixops/generic_operation.cpp
  tests/regressions/python/exception_swallowed_369.py
  tests/unit/execution_tree/compiler.cpp
Labels: submodule: backend

#479 Improve CircleCI configuration
  .circleci/config.yml
  tools/docker/base/Dockerfile
  tools/docker/circleci/Dockerfile
Labels: category: continuous integration

#483 Attempting to fix GIL issues while printing from PhySL
  python/src/bindings/ostream.hpp
  python/src/init_hpx.cpp
Labels: category: @Phylanx, type: enhancement

#485 Resolve ticket 442, implementing np.array and np.zeros
  python/phylanx/ast/transformation.py
  tests/unit/python/execution_tree/make_array.py
Labels: category: @Phylanx, category: PhySL, type: enhancement

#438 Adding Linear solver primitive with different decompositions
  .circleci/config.yml
  phylanx/include/plugins.hpp
  phylanx/plugins/solvers/linear_solver.hpp
  phylanx/plugins/solvers/solvers.hpp
  src/plugins/CMakeLists.txt
  src/plugins/solvers/CMakeLists.txt
  src/plugins/solvers/linear_solver.cpp
  src/plugins/solvers/solvers.cpp
  tests/regressions/execution_tree/assign_wrong_variable_245.cpp
  tests/unit/plugins/CMakeLists.txt
  tests/unit/plugins/solvers/CMakeLists.txt
  tests/unit/plugins/solvers/linear_solver.cpp
Labels: category: algorithms, category: primitives, type: enhancement

#487 Making sure 1d integer arrays get properly converted to node_data<int64_t>
  phylanx/execution_tree/compiler/actors.hpp
  python/phylanx/ast/transformation.py
  python/src/bindings/type_casters.hpp
  tests/regressions/python/CMakeLists.txt
  tests/regressions/python/array_shape_486.py
  tests/regressions/python/passing_compiler_state_453.py
Labels: category: @Phylanx, category: PhySL, type: enhancement

#488 Various minor changes cleaning up things
  .clang-format
  phylanx/ast/node.hpp
  phylanx/execution_tree/compiler/compiler.hpp
  phylanx/execution_tree/primitives/base_primitive.hpp
  phylanx/execution_tree/primitives/define_function.hpp
  phylanx/execution_tree/primitives/primitive_component_base.hpp
  src/ast/node.cpp
  src/execution_tree/compiler/compiler.cpp
  src/execution_tree/primitives/base_primitive.cpp
  src/execution_tree/primitives/function_reference.cpp
  src/execution_tree/primitives/primitive_component_base.cpp
  tests/regressions/execution_tree/list_of_variables_244.cpp
  tests/unit/ast/to_string.cpp
Labels: category: PhySL, type: enhancement

#497 Setup HPX dependencies for PyBind targets
  python/src/CMakeLists.txt
Labels: category: CMake, type: enhancement

#496 Adding decomposition primitive
  phylanx/plugins/solvers/decomposition.hpp
  phylanx/plugins/solvers/solvers.hpp
  src/plugins/solvers/decomposition.cpp
  src/plugins/solvers/solvers.cpp
  tests/regressions/execution_tree/assign_wrong_variable_245.cpp
  tests/unit/plugins/solvers/CMakeLists.txt
  tests/unit/plugins/solvers/decomposition.cpp
Labels: category: PhySL, category: primitives, type: enhancement

#504 Fix phylanxrun.py
  cmake/templates/phylanxrun.py.in
Labels: type: defect, type: enhancement
