Repository STEllAR-GROUP/phylanx, pull requests merged in 2018-12, with the labels that each got.

#673 Squeeze primitive
  phylanx/plugins/matrixops/matrixops.hpp
  phylanx/plugins/matrixops/squeeze_operation.hpp
  src/plugins/matrixops/matrixops.cpp
  src/plugins/matrixops/squeeze_operation.cpp
  tests/unit/plugins/matrixops/CMakeLists.txt
  tests/unit/plugins/matrixops/squeeze_operation.cpp
Labels: category: primitives, submodule: backend, type: enhancement

#680 Fixing how identity handles non-integer inputs
  phylanx/plugins/matrixops/identity.hpp
  src/plugins/matrixops/identity.cpp
  tests/unit/plugins/matrixops/identity.cpp
Labels: category: primitives, type: compatibility issue, type: enhancement

#671 Provide an error on illegal returns
  python/phylanx/ast/physl.py
  tests/unit/python/execution_tree/CMakeLists.txt
  tests/unit/python/execution_tree/multi_return.py
Labels: category: @Phylanx, submodule: frontend, type: enhancement

#648 Python K-Means generate arbitrary random points
  examples/algorithms/CMakeLists.txt
  examples/algorithms/kmeans/CMakeLists.txt
  examples/algorithms/kmeans/kmeans.cpp
  examples/algorithms/kmeans/kmeans.numpy.py
  examples/algorithms/kmeans/kmeans.phylanx.py
Labels: category: algorithms, type: enhancement

#672 Adding unique primitive
  phylanx/plugins/matrixops/matrixops.hpp
  phylanx/plugins/matrixops/unique.hpp
  src/plugins/matrixops/matrixops.cpp
  src/plugins/matrixops/unique.cpp
  tests/unit/plugins/matrixops/CMakeLists.txt
  tests/unit/plugins/matrixops/unique.cpp
Labels: category: primitives, type: enhancement

#686 Generic_Operation: sinh, cosh and tanh are added
  phylanx/plugins/matrixops/generic_operation.hpp
  src/plugins/matrixops/generic_operation.cpp
  tests/unit/plugins/matrixops/generic_operation.cpp
Labels: submodule: backend, type: enhancement

#685 Adding flatten primitive
  phylanx/plugins/matrixops/flatten.hpp
  phylanx/plugins/matrixops/matrixops.hpp
  src/plugins/matrixops/flatten.cpp
  src/plugins/matrixops/matrixops.cpp
  tests/unit/plugins/matrixops/CMakeLists.txt
  tests/unit/plugins/matrixops/flatten.cpp
Labels: category: primitives, type: enhancement

#695 Fix int strict helper
  phylanx/execution_tree/primitives/base_primitive.hpp
Labels: submodule: backend, type: enhancement

#693 Changing the double type to general T type for 2d cases
  src/plugins/matrixops/flatten.cpp
Labels: category: primitives, type: compatibility issue, type: enhancement

#692 Adding prod primitive
  phylanx/plugins/arithmetics/arithmetics.hpp
  phylanx/plugins/arithmetics/cumsum.hpp
  phylanx/plugins/arithmetics/prod_operation.hpp
  phylanx/plugins/arithmetics/sum_operation.hpp
  phylanx/plugins/matrixops/matrixops.hpp
  src/plugins/arithmetics/arithmetics.cpp
  src/plugins/arithmetics/cumsum.cpp
  src/plugins/arithmetics/prod_operation.cpp
  src/plugins/arithmetics/sum_operation.cpp
  src/plugins/matrixops/matrixops.cpp
  tests/unit/plugins/arithmetics/CMakeLists.txt
  tests/unit/plugins/arithmetics/cumsum.cpp
  tests/unit/plugins/arithmetics/prod_operation.cpp
  tests/unit/plugins/arithmetics/sum_operation.cpp
  tests/unit/plugins/matrixops/CMakeLists.txt
Labels: category: primitives, type: compatibility issue, type: enhancement

#687 Fix issue 609
  tests/unit/execution_tree/primitives/dictionary.cpp
Labels: category: tests, type: enhancement

#683 Fixing minor issues with extract_shape and generic operations primitives
  src/plugins/matrixops/generic_operation.cpp
Labels: category: primitives, type: compatibility issue, type: enhancement

#681 Eye primitive
  phylanx/plugins/matrixops/eye_operation.hpp
  phylanx/plugins/matrixops/matrixops.hpp
  src/plugins/matrixops/eye_operation.cpp
  src/plugins/matrixops/matrixops.cpp
  tests/unit/plugins/matrixops/CMakeLists.txt
  tests/unit/plugins/matrixops/eye_operation.cpp
Labels: category: primitives, submodule: backend, type: enhancement

#682 Modifying squeeze primitive arguments
  src/plugins/matrixops/squeeze_operation.cpp
Labels: category: primitives, type: compatibility issue, type: enhancement

#690 Fixes the problem with returns from inner functions.
  python/phylanx/ast/physl.py
  tests/unit/python/execution_tree/multi_return.py
Labels: category: @Phylanx, submodule: frontend, type: defect

#691 Adding Reshape primitive
  phylanx/plugins/matrixops/matrixops.hpp
  phylanx/plugins/matrixops/reshape_operation.hpp
  src/plugins/matrixops/matrixops.cpp
  src/plugins/matrixops/reshape_operation.cpp
  tests/unit/plugins/matrixops/CMakeLists.txt
  tests/unit/plugins/matrixops/eye_operation.cpp
  tests/unit/plugins/matrixops/reshape_operation.cpp
Labels: category: primitives, submodule: backend

#694 Adding Tile primitive
  phylanx/plugins/matrixops/matrixops.hpp
  phylanx/plugins/matrixops/tile_operation.hpp
  src/plugins/matrixops/matrixops.cpp
  src/plugins/matrixops/tile_operation.cpp
  tests/unit/plugins/matrixops/CMakeLists.txt
  tests/unit/plugins/matrixops/tile_operation.cpp
Labels: category: primitives, submodule: backend

#688 Adding Softmax operation
  phylanx/plugins/matrixops/matrixops.hpp
  phylanx/plugins/matrixops/softmax_operation.hpp
  src/plugins/matrixops/matrixops.cpp
  src/plugins/matrixops/softmax_operation.cpp
  tests/unit/plugins/matrixops/CMakeLists.txt
  tests/unit/plugins/matrixops/softmax_operation.cpp
Labels: category: primitives, submodule: backend, type: enhancement

#696 Eye Primitive: modified `match_data` to accept dtype
  src/plugins/matrixops/eye_operation.cpp
Labels: category: primitives, type: compatibility issue, type: enhancement

#675 Dynamic configuration of HPX.
  cmake/templates/__init__.py.in
  python/phylanx/ast/physl.py
  python/phylanx/core/config.py
  python/phylanx/execution_tree/__init__.py
  python/src/init_hpx.cpp
  python/src/init_hpx.hpp
  python/src/phylanx.cpp
  tests/regressions/python/466_compiler_problems.py
  tests/regressions/python/passing_compiler_state_453.py
  tests/unit/python/ast/generate_ast.py
  tests/unit/python/ast/node.py
  tests/unit/python/ast/python_builds_ast.py
  tests/unit/python/ast/traverse_ast.py
  tests/unit/python/execution_tree/CMakeLists.txt
  tests/unit/python/execution_tree/config_hpx.py
  tests/unit/python/execution_tree/dynamic_init.py
  tests/unit/python/execution_tree/eval.py
  tests/unit/python/execution_tree/make_array.py
  tests/unit/python/execution_tree/multi_init.py
Labels: category: @Phylanx, submodule: frontend, type: enhancement

#700 Modifying squeeze primitive not to search for the dtype
  src/plugins/matrixops/squeeze_operation.cpp
Labels: type: defect

#703 Modifying reshape primitive, reshape1d_to_2d
  src/plugins/matrixops/reshape_operation.cpp
Labels: category: primitives, type: enhancement

#704 Propagate dtype
  phylanx/execution_tree/primitives/base_primitive.hpp
  phylanx/plugins/arithmetics/prod_operation.hpp
  phylanx/plugins/arithmetics/statistics.hpp
  phylanx/plugins/arithmetics/statistics_impl.hpp
  phylanx/plugins/arithmetics/sum_operation.hpp
  phylanx/plugins/matrixops/cross_operation.hpp
  phylanx/plugins/matrixops/determinant.hpp
  phylanx/plugins/matrixops/diag_operation.hpp
  phylanx/plugins/matrixops/dot_operation.hpp
  phylanx/plugins/matrixops/extract_shape.hpp
  phylanx/plugins/matrixops/gradient_operation.hpp
  phylanx/plugins/matrixops/inverse_operation.hpp
  phylanx/plugins/matrixops/linearmatrix.hpp
  phylanx/plugins/matrixops/linspace.hpp
  phylanx/plugins/matrixops/mean_operation.hpp
  phylanx/plugins/matrixops/power_operation.hpp
  phylanx/plugins/matrixops/shuffle_operation.hpp
  phylanx/plugins/matrixops/transpose_operation.hpp
  python/phylanx/ast/physl.py
  src/execution_tree/primitives/base_primitive.cpp
  src/plugins/arithmetics/prod_operation.cpp
  src/plugins/arithmetics/sum_operation.cpp
  src/plugins/matrixops/cross_operation.cpp
  src/plugins/matrixops/determinant.cpp
  src/plugins/matrixops/diag_operation.cpp
  src/plugins/matrixops/dot_operation.cpp
  src/plugins/matrixops/extract_shape.cpp
  src/plugins/matrixops/gradient_operation.cpp
  src/plugins/matrixops/inverse_operation.cpp
  src/plugins/matrixops/linearmatrix.cpp
  src/plugins/matrixops/linspace.cpp
  src/plugins/matrixops/mean_operation.cpp
  src/plugins/matrixops/power_operation.cpp
  src/plugins/matrixops/shuffle_operation.cpp
  src/plugins/matrixops/transpose_operation.cpp
  tests/unit/plugins/arithmetics/prod_operation.cpp
  tests/unit/plugins/matrixops/extract_shape.cpp
  tests/unit/plugins/matrixops/inverse_operation.cpp
  tests/unit/plugins/matrixops/power_operation.cpp
Labels: category: primitives, submodule: backend, type: compatibility issue, type: enhancement

#707 Make sure the [vhd]stack primitives accept lists as any of their arguments
  phylanx/execution_tree/primitives/base_primitive.hpp
  src/execution_tree/primitives/base_primitive.cpp
  src/plugins/controls/fold_left_operation.cpp
  src/plugins/controls/fold_right_operation.cpp
  src/plugins/matrixops/stack_operation.cpp
  tests/regressions/execution_tree/319_fold_right_copy_list.cpp
  tests/regressions/execution_tree/CMakeLists.txt
Labels: category: primitives, type: compatibility issue, type: enhancement

#711 Fixing compilation problems if no tensor support is available
  phylanx/execution_tree/primitives/node_data_helpers.hpp
  src/plugins/matrixops/slicing_operation.cpp
Labels: type: enhancement

#706 Creating statistics plugin
  .circleci/config.yml
  phylanx/execution_tree/compiler/actors.hpp
  phylanx/include/plugins.hpp
  phylanx/plugins/arithmetics/arithmetics.hpp
  phylanx/plugins/arithmetics/generic_operation_0d.hpp
  phylanx/plugins/arithmetics/generic_operation_1d.hpp
  phylanx/plugins/arithmetics/generic_operation_2d.hpp
  phylanx/plugins/arithmetics/generic_operation_3d.hpp
  phylanx/plugins/matrixops/matrixops.hpp
  phylanx/plugins/matrixops/mean_operation.hpp
  phylanx/plugins/statistics/max_operation.hpp
  phylanx/plugins/statistics/mean_operation.hpp
  phylanx/plugins/statistics/min_operation.hpp
  phylanx/plugins/statistics/prod_operation.hpp
  phylanx/plugins/statistics/statistics.hpp
  phylanx/plugins/statistics/statistics_base.hpp
  phylanx/plugins/statistics/statistics_base_impl.hpp
  phylanx/plugins/statistics/std_operation.hpp
  phylanx/plugins/statistics/sum_operation.hpp
  phylanx/plugins/statistics/var_operation.hpp
  src/plugins/CMakeLists.txt
  src/plugins/arithmetics/arithmetics.cpp
  src/plugins/arithmetics/generic_operation.cpp
  src/plugins/matrixops/matrixops.cpp
  src/plugins/matrixops/mean_operation.cpp
  src/plugins/statistics/CMakeLists.txt
  src/plugins/statistics/max_operation.cpp
  src/plugins/statistics/mean_operation.cpp
  src/plugins/statistics/min_operation.cpp
  src/plugins/statistics/prod_operation.cpp
  src/plugins/statistics/statistics.cpp
  src/plugins/statistics/std_operation.cpp
  src/plugins/statistics/sum_operation.cpp
  src/plugins/statistics/var_operation.cpp
  tests/unit/plugins/CMakeLists.txt
  tests/unit/plugins/arithmetics/CMakeLists.txt
  tests/unit/plugins/arithmetics/generic_operation.cpp
  tests/unit/plugins/matrixops/CMakeLists.txt
  tests/unit/plugins/statistics/CMakeLists.txt
  tests/unit/plugins/statistics/max_operation.cpp
  tests/unit/plugins/statistics/mean_operation.cpp
  tests/unit/plugins/statistics/min_operation.cpp
  tests/unit/plugins/statistics/prod_operation.cpp
  tests/unit/plugins/statistics/std_operation.cpp
  tests/unit/plugins/statistics/sum_operation.cpp
  tests/unit/plugins/statistics/var_operation.cpp
Labels: category: primitives, type: enhancement

#713 Fixing reshape primitive 2d->2d reshaping to properly work with vectorization
  phylanx/util/matrix_iterators.hpp
  src/plugins/matrixops/reshape_operation.cpp
Labels: category: primitives, platform: Intel KNL, submodule: backend, type: enhancement
