Repository STEllAR-GROUP/phylanx, pull requests merged in 2018-11, with the labels that each got.

#645 Fix #639.
  python/phylanx/ast/physl.py
  tests/unit/python/execution_tree/primitives/numpy_dtype.py
Labels: category: @Phylanx, type: enhancement

#646 Change constant() to support ...like and empty operations
  phylanx/plugins/matrixops/constant.hpp
  src/execution_tree/primitives/base_primitive.cpp
  src/plugins/matrixops/arange.cpp
  src/plugins/matrixops/constant.cpp
  src/plugins/matrixops/cumsum.cpp
  src/plugins/matrixops/hstack_operation.cpp
  src/plugins/matrixops/identity.cpp
  src/plugins/matrixops/matrixops.cpp
  src/plugins/matrixops/vstack_operation.cpp
  tests/unit/plugins/matrixops/constant.cpp
Labels: category: PhySL, category: primitives, type: compatibility issue, type: enhancement

#654 initial import of randomforest
  examples/algorithms/randomforest/np_randomforest.py
Labels: category: algorithms, category: examples

#649 Add parallel_block capability to Phylanx
  python/phylanx/__init__.py
  python/phylanx/ast/physl.py
  python/phylanx/execution_tree/__init__.py
  tests/unit/python/execution_tree/CMakeLists.txt
  tests/unit/python/execution_tree/parallel.py
Labels: submodule: frontend

#661 Fix Steve's checker
  .circleci/config.yml
Labels: category: continuous integration

#664 Fixing the std::bad_alloc error seen with clang
  src/plugins/algorithms/als.cpp
Labels: category: primitives, type: enhancement

#666 Adding dtype support to vstack() and hstack()
  python/phylanx/ast/physl.py
  tests/regressions/python/651_vstack_dtype.py
  tests/regressions/python/CMakeLists.txt
Labels: category: @Phylanx, compiler: python, type: compatibility issue, type: enhancement

#670 Use Blaze master instead of 4.2
  tools/docker/base/Dockerfile
Labels: category: continuous integration

#676 Fixing compilation problems of action based primitives
  tests/unit/distributed/remote_run.cpp
Labels: category: primitives, type: compatibility issue, type: enhancement

#678 Fix CircleCI running out of memory with -j1
  .circleci/config.yml
Labels: category: continuous integration, type: enhancement
