Repository STEllAR-GROUP/phylanx, pull requests merged in 2019-08, with the labels that each got.

#1009 Fixing lifetime of returned Python objects
  python/src/bindings/variable.cpp
  python/src/bindings/variable.hpp
Labels: category: @Phylanx, type: enhancement

#1006 Adding 4D array support to node_data
  phylanx/ast/node.hpp
  phylanx/ast/parser/expression.hpp
  phylanx/ast/parser/expression_def.hpp
  phylanx/config.hpp
  phylanx/execution_tree/primitives/primitive_argument_type.hpp
  phylanx/ir/node_data.hpp
  phylanx/plugins/matrixops/constant.hpp
  phylanx/util/serialization/blaze.hpp
  src/ir/node_data.cpp
  src/plugins/matrixops/constant.cpp
  tests/regressions/execution_tree/negative_integral_value_131.cpp
  tests/unit/ir/node_data.cpp
  tests/unit/plugins/matrixops/constant.cpp
Labels: category: primitives, submodule: backend, type: enhancement

#1017 Update conv.xsl url
  .circleci/config.yml
Labels: category: continuous integration

#1019 Adding missing exports
  src/plugins/common/dot_operation_double.cpp
  src/plugins/common/dot_operation_int64.cpp
  src/plugins/common/dot_operation_uint8.cpp
Labels: category: primitives, type: compatibility issue, type: enhancement

#1014 Attempting to work around MSVC running into an OOM condition
  phylanx/plugins/arithmetics/generic_operation_3d.hpp
  phylanx/plugins/arithmetics/generic_operation_3d_definitions.hpp
  src/plugins/arithmetics/generic_operation_3d_float_1.cpp
  src/plugins/arithmetics/generic_operation_3d_float_2.cpp
  src/plugins/arithmetics/generic_operation_3d_int64_1.cpp
  src/plugins/arithmetics/generic_operation_3d_int64_2.cpp
Labels: category: primitives, type: compatibility issue

#1018 Adding spatial_2d_padding operation
  phylanx/plugins/keras_support/keras_support.hpp
  phylanx/plugins/keras_support/spatial_2d_padding_operation.hpp
  src/execution_tree/primitives/base_primitive.cpp
  src/plugins/keras_support/keras_support.cpp
  src/plugins/keras_support/spatial_2d_padding_operation.cpp
  tests/unit/plugins/keras_support/CMakeLists.txt
  tests/unit/plugins/keras_support/spatial_2d_padding_operation.cpp
Labels: category: primitives, platform: KERAS, submodule: backend

#1021 Adding 4D support to expand_dims
  phylanx/plugins/matrixops/expand_dims.hpp
  src/plugins/matrixops/expand_dims.cpp
  tests/unit/plugins/matrixops/expand_dims.cpp
Labels: category: primitives, submodule: backend, type: enhancement

#1012 More #include fixes for recent HPX changes
  src/execution_tree/annotation.cpp
  src/execution_tree/localities_annotation.cpp
  src/execution_tree/tiling_annotations.cpp
Labels: type: compatibility issue, type: enhancement

#1024 Adding 4D support to random
  phylanx/plugins/matrixops/random.hpp
  src/plugins/matrixops/random.cpp
  tests/unit/plugins/matrixops/random.cpp
  tests/unit/plugins/matrixops/random_distributions.cpp
Labels: category: primitives, submodule: backend, type: enhancement

#1023 Adding Python bindings for 4d arrays
  python/src/bindings/execution_tree.cpp
  python/src/bindings/type_casters.hpp
Labels: category: @Phylanx, type: compatibility issue, type: enhancement

#1029 Adding 4D support to extract_shape operation
  phylanx/execution_tree/localities_annotation.hpp
  phylanx/plugins/matrixops/extract_shape.hpp
  src/execution_tree/localities_annotation.cpp
  src/plugins/matrixops/extract_shape.cpp
  tests/unit/plugins/matrixops/extract_shape.cpp
Labels: category: primitives, submodule: backend, type: enhancement

#1025 Adding 4D support to len operation
  src/plugins/listops/len_operation.cpp
  tests/unit/plugins/listops/len_operation.cpp
Labels: category: primitives, submodule: backend, type: enhancement

#1030 Adding 4D support for transpose operation
  phylanx/plugins/common/transpose_operation_nd.hpp
  src/plugins/common/transpose_operation_nd.cpp
  src/plugins/matrixops/transpose_operation.cpp
  tests/unit/plugins/matrixops/transpose_operation.cpp
Labels: category: primitives, submodule: backend, type: enhancement

#1033 Updating pool2d to accept 4d arrays as input
  phylanx/plugins/keras_support/avg_pool2d_operation.hpp
  phylanx/plugins/keras_support/max_pool2d_operation.hpp
  src/plugins/keras_support/avg_pool2d_operation.cpp
  src/plugins/keras_support/conv1d_operation.cpp
  src/plugins/keras_support/max_pool2d_operation.cpp
  tests/unit/plugins/keras_support/avg_pool2d_operation.cpp
  tests/unit/plugins/keras_support/max_pool2d_operation.cpp
Labels: category: primitives, platform: KERAS, type: enhancement

#1034 Updating resize_images to accept 4d arrays as input
  src/plugins/keras_support/resize_operation.cpp
  tests/unit/plugins/keras_support/resize_operation.cpp
Labels: platform: KERAS, type: enhancement
