Repository STEllAR-GROUP/phylanx, pull requests merged in 2019-03, with the labels that each got.

#807 Function call attributes
  phylanx/ast/detail/is_function_call.hpp
  phylanx/ast/node.hpp
  phylanx/ast/parser/ast.hpp
  phylanx/ast/parser/expression.hpp
  phylanx/ast/parser/expression_def.hpp
  phylanx/ast/traverse.hpp
  phylanx/execution_tree/compile.hpp
  phylanx/execution_tree/compiler/actors.hpp
  phylanx/execution_tree/compiler/compiler.hpp
  phylanx/execution_tree/compiler/locality_attribute.hpp
  phylanx/execution_tree/compiler/primitive_name.hpp
  phylanx/execution_tree/compiler_component.hpp
  phylanx/execution_tree/primitives/debug_output.hpp
  phylanx/execution_tree/primitives/primitive_argument_type.hpp
  phylanx/execution_tree/primitives/primitive_component.hpp
  phylanx/include/compile.hpp
  phylanx/ir/node_data.hpp
  phylanx/ir/ranges.hpp
  phylanx/plugins/matrixops/insert.hpp
  phylanx/plugins/matrixops/squeeze_operation.hpp
  phylanx/util/serialization/blaze.hpp
  phylanx/util/serialization/variant.hpp
  python/phylanx/ast/physl.py
  python/phylanx/ast/transducer.py
  python/src/bindings/binding_helpers.cpp
  src/ast/detail/is_function_call.cpp
  src/ast/node.cpp
  src/execution_tree/compile.cpp
  src/execution_tree/compiler/actors.cpp
  src/execution_tree/compiler/compiler.cpp
  src/execution_tree/compiler/locality_attribute.cpp
  src/execution_tree/compiler/primitive_name.cpp
  src/execution_tree/compiler_component.cpp
  src/execution_tree/patterns.cpp
  src/execution_tree/primitives/base_primitive.cpp
  src/execution_tree/primitives/debug_output.cpp
  src/execution_tree/primitives/primitive_argument_type.cpp
  src/execution_tree/primitives/primitive_component.cpp
  src/ir/ranges.cpp
  tests/regressions/execution_tree/expression_topology_213.cpp
  tests/unit/ast/generate_ast.cpp
  tests/unit/ast/to_string.cpp
  tests/unit/distributed/CMakeLists.txt
  tests/unit/distributed/define_locality.cpp
  tests/unit/distributed/remote_add.cpp
  tests/unit/distributed/remote_run.cpp
  tests/unit/execution_tree/CMakeLists.txt
  tests/unit/execution_tree/compiler_component.cpp
  tests/unit/execution_tree/define_locality.cpp
  tests/unit/execution_tree/expression_topology.cpp
  tests/unit/execution_tree/parse_primitive_name.cpp
Labels: submodule: backend, type: enhancement

#802 Fixing currently failing remote test
  .circleci/config.yml
  tests/unit/distributed/remote_run.cpp
Labels: category: tests, type: enhancement

#823 Adding 3D support to the reshape and merging flatten to reshape
  phylanx/plugins/matrixops/flatten.hpp
  phylanx/plugins/matrixops/matrixops.hpp
  phylanx/plugins/matrixops/reshape_operation.hpp
  src/plugins/matrixops/flatten.cpp
  src/plugins/matrixops/matrixops.cpp
  src/plugins/matrixops/reshape_operation.cpp
  tests/unit/plugins/matrixops/CMakeLists.txt
  tests/unit/plugins/matrixops/flatten.cpp
  tests/unit/plugins/matrixops/reshape_operation.cpp
Labels: category: primitives

#818 Add test for range::size(), handle empty int ranges
  phylanx/ir/ranges.hpp
  src/ir/ranges.cpp
  tests/unit/ir/ranges.cpp
Labels: type: enhancement

#798 hyperlda
  examples/algorithms/datasets/docword.kos.train.mat
  examples/algorithms/datasets/docword.nips.train.mat
  examples/algorithms/lda/ldahyper.py
  examples/algorithms/lda/physl_ldahyper.py
Labels: category: algorithms, category: examples, compiler: python

#809 Build Docs only for master
  .circleci/config.yml
  cmake/templates/generate_rst.py.in
  docs/CMakeLists.txt
Labels: category: documentation, type: enhancement

#824 Check CircleCI test coverage
  .circleci/config.yml
  tools/circleci/check_test_coverage.py
Labels: category: continuous integration, category: tests, type: enhancement

#814 Adapt slicing to support 32 bit indices
  phylanx/execution_tree/primitives/slice_node_data_2d.hpp
Labels: type: compatibility issue

#805 Add support to eval method.
  python/phylanx/ast/physl.py
  python/phylanx/ast/transducer.py
  python/src/bindings/execution_tree.cpp
  python/src/bindings/type_casters.hpp
  src/execution_tree/primitives/access_argument.cpp
  src/execution_tree/primitives/primitive_component.cpp
  tests/regressions/python/805_lazy_variable.py
  tests/regressions/python/805_two_variables.py
  tests/regressions/python/CMakeLists.txt
  tests/unit/python/execution_tree/CMakeLists.txt
  tests/unit/python/execution_tree/lazy_eval.py
Labels: category: @Phylanx, submodule: frontend, type: feature request

#828 Adding support for default arguments to PhySL and frontend
  phylanx/execution_tree/compiler/compiler.hpp
  python/phylanx/ast/physl.py
  src/execution_tree/compiler/compiler.cpp
  src/execution_tree/primitives/access_argument.cpp
  tests/regressions/python/826_default_args.py
  tests/unit/execution_tree/compiler.cpp
Labels: category: @Phylanx, category: PhySL, compiler: python, submodule: backend, submodule: frontend, type: compatibility issue, type: enhancement

#831 Fix deploy
  .circleci/config.yml
  CMakeLists.txt
Labels: category: continuous integration, type: defect

#820 Making sure 'nil' is properly handled by various primitives
  phylanx/ast/node.hpp
  phylanx/execution_tree/primitives/primitive_argument_type.hpp
  phylanx/execution_tree/primitives/primitive_component_base.hpp
  phylanx/plugins/booleans/comparison_impl.hpp
  src/ast/node.cpp
  src/execution_tree/compiler/compiler.cpp
  src/execution_tree/primitives/lambda.cpp
  src/util/slicing_helpers.cpp
  tests/regressions/execution_tree/817_compare_nil.cpp
  tests/regressions/execution_tree/817_cout_nil.cpp
  tests/regressions/execution_tree/817_lambda_nil.cpp
  tests/regressions/execution_tree/CMakeLists.txt
Labels: category: primitives, type: compatibility issue

#833 Install Phylanx Python in image. Tidy CCI config.
  .circleci/config.yml
  tools/docker/circleci/Dockerfile
Labels: category: @Phylanx, category: continuous integration, type: enhancement

#816 Steps towards resolving ticket 808
  python/phylanx/ast/physl.py
  python/src/CMakeLists.txt
  python/src/bindings/util.cpp
  src/execution_tree/compiler/compiler.cpp
  src/execution_tree/primitives/debug_output.cpp
  tests/regressions/python/808_print_twice.py
  tests/regressions/python/CMakeLists.txt
  tests/regressions/python/create_list_409.py
  tests/regressions/python/name_constants_411.py
  tests/unit/execution_tree/compiler.cpp
  tests/unit/util/performance_data.cpp
Labels: category: @Phylanx, type: compatibility issue, type: enhancement

#838 Making sure 'None' can be used as a default argument
  phylanx/util/repr_manip.hpp
  python/src/bindings/binding_helpers.cpp
  src/execution_tree/primitives/access_argument.cpp
  src/util/repr_manip.cpp
  tests/regressions/python/837_none_default_argument.py
  tests/regressions/python/CMakeLists.txt
Labels: category: @Phylanx, type: compatibility issue, type: enhancement

#841 Fix inspect dependency on core
  .circleci/config.yml
  tools/inspect/CMakeLists.txt
Labels: category: CMake, category: continuous integration, type: enhancement

#836 Actually testing things in 817_cout_nil
  tests/regressions/execution_tree/817_cout_nil.cpp
  tests/regressions/execution_tree/CMakeLists.txt
Labels: category: tests, type: enhancement

#840 Fixing extraction of performance data in the frontend
  python/phylanx/ast/physl.py
  python/src/bindings/binding_helpers.cpp
  src/util/performance_data.cpp
  tests/regressions/python/832_performance_data.py
  tests/regressions/python/CMakeLists.txt
Labels: category: @Phylanx, category: PhySL, type: enhancement

#847 Fixing how statistics primitives handle negative axis when axes are passed as a list
  phylanx/plugins/statistics/statistics_base_impl.hpp
  tests/unit/plugins/statistics/all_operation.cpp
  tests/unit/plugins/statistics/any_operation.cpp
  tests/unit/plugins/statistics/max_operation.cpp
  tests/unit/plugins/statistics/mean_operation.cpp
  tests/unit/plugins/statistics/min_operation.cpp
  tests/unit/plugins/statistics/sum_operation.cpp
Labels: category: primitives, type: enhancement

#848 Add support to IfExp construct.
  python/phylanx/ast/physl.py
  tests/regressions/python/846_if_expression.py
  tests/regressions/python/CMakeLists.txt
Labels: category: @Phylanx, type: enhancement

#851 This fixes the way None is printed.
  phylanx/include/util.hpp
  phylanx/util/none_manip.hpp
  python/src/bindings/binding_helpers.cpp
  src/ast/node.cpp
  src/util/none_manip.cpp
Labels: category: primitives, type: compatibility issue, type: enhancement

#806 Adding functionality to get the phylanx internal type id and name.
  phylanx/execution_tree/primitives.hpp
  phylanx/execution_tree/primitives/base_primitive.hpp
  phylanx/execution_tree/primitives/phyname.hpp
  phylanx/execution_tree/primitives/phytype.hpp
  phylanx/execution_tree/primitives/primitive_argument_type.hpp
  src/execution_tree/patterns.cpp
  src/execution_tree/primitives/base_primitive.cpp
  src/execution_tree/primitives/phyname.cpp
  src/execution_tree/primitives/phytype.cpp
  tests/unit/python/execution_tree/eval.py
Labels: category: primitives, type: enhancement

#850 Adding 3D support for the softmax operation
  phylanx/plugins/matrixops/softmax_operation.hpp
  src/plugins/matrixops/softmax_operation.cpp
  tests/unit/plugins/matrixops/softmax_operation.cpp
Labels: category: primitives, submodule: backend, type: enhancement

#834 Fixing 0dim case for random
  python/src/bindings/binding_helpers.cpp
  src/plugins/matrixops/random.cpp
  tests/regressions/python/827_random_0dim.py
  tests/regressions/python/CMakeLists.txt
  tests/unit/plugins/matrixops/random.cpp
Labels: category: @Phylanx, type: compatibility issue, type: enhancement

#845 Adding generic_primitive_bool with is_nan, isinf, isfinite, isneginf,and isposinf
  phylanx/plugins/arithmetics/arithmetics.hpp
  phylanx/plugins/arithmetics/generic_operation_0d.hpp
  phylanx/plugins/arithmetics/generic_operation_1d.hpp
  phylanx/plugins/arithmetics/generic_operation_bool.hpp
  phylanx/plugins/arithmetics/generic_operation_bool_nd.hpp
  src/ir/node_data.cpp
  src/plugins/arithmetics/arithmetics.cpp
  src/plugins/arithmetics/generic_operation_bool.cpp
  src/plugins/arithmetics/generic_operation_bool_0d_float.cpp
  src/plugins/arithmetics/generic_operation_bool_0d_int64.cpp
  src/plugins/arithmetics/generic_operation_bool_1d_float.cpp
  src/plugins/arithmetics/generic_operation_bool_1d_int64.cpp
  src/plugins/arithmetics/generic_operation_bool_2d_float.cpp
  src/plugins/arithmetics/generic_operation_bool_2d_int64.cpp
  src/plugins/arithmetics/generic_operation_bool_3d_float.cpp
  src/plugins/arithmetics/generic_operation_bool_3d_int64.cpp
  src/plugins/listops/listops.cpp
  tests/unit/plugins/arithmetics/CMakeLists.txt
  tests/unit/plugins/arithmetics/generic_operation_bool.cpp
Labels: category: primitives, type: compatibility issue, type: enhancement

#853 Making sure concatenate accepts lists of variables
  phylanx/execution_tree/primitives/primitive_argument_type.hpp
  phylanx/plugins/matrixops/concatenate.hpp
  src/execution_tree/primitives/access_argument.cpp
  src/execution_tree/primitives/access_variable.cpp
  src/execution_tree/primitives/variable.cpp
  src/plugins/matrixops/concatenate.cpp
  tests/regressions/python/852_concatenate_list.py
  tests/regressions/python/CMakeLists.txt
Labels: category: primitives, type: compatibility issue, type: enhancement

#856 Adding support to execution_tree.var() to expose the numpy dtype of the value it holds
  phylanx/execution_tree/primitives/primitive_argument_type.hpp
  python/phylanx/ast/physl.py
  python/src/bindings/binding_helpers.cpp
  python/src/bindings/binding_helpers.hpp
  python/src/bindings/execution_tree.cpp
  src/execution_tree/primitives/phyname.cpp
  src/execution_tree/primitives/phytype.cpp
  tests/unit/python/execution_tree/eval.py
Labels: category: @Phylanx, category: PhySL, category: primitives, type: compatibility issue, type: enhancement

#858 Making sure initial value for statistics primitives works as advertized
  phylanx/plugins/statistics/statistics_base_impl.hpp
  tests/unit/plugins/statistics/max_operation.cpp
  tests/unit/plugins/statistics/min_operation.cpp
  tests/unit/plugins/statistics/prod_operation.cpp
  tests/unit/plugins/statistics/sum_operation.cpp
Labels: category: primitives, type: enhancement

#860 Sign primitive returns correct type
  phylanx/plugins/arithmetics/generic_operation.hpp
  src/plugins/arithmetics/arithmetics.cpp
  src/plugins/arithmetics/generic_operation.cpp
  tests/unit/plugins/arithmetics/generic_operation.cpp
Labels: category: primitives, type: compatibility issue, type: enhancement

#861 Fixing internal type the statistics primitives operate on
  phylanx/plugins/statistics/statistics_base.hpp
  phylanx/plugins/statistics/statistics_base_impl.hpp
  src/plugins/statistics/all_operation.cpp
  src/plugins/statistics/any_operation.cpp
  src/plugins/statistics/logsumexp_operation.cpp
  src/plugins/statistics/max_operation.cpp
  src/plugins/statistics/mean_operation.cpp
  src/plugins/statistics/min_operation.cpp
  src/plugins/statistics/prod_operation.cpp
  src/plugins/statistics/std_operation.cpp
  src/plugins/statistics/sum_operation.cpp
  src/plugins/statistics/var_operation.cpp
  tests/unit/plugins/statistics/logsumexp_operation.cpp
  tests/unit/plugins/statistics/std_operation.cpp
  tests/unit/plugins/statistics/var_operation.cpp
Labels: category: primitives, type: compatibility issue, type: enhancement

#863 Moving softmax to its own plugin
  .circleci/config.yml
  phylanx/include/plugins.hpp
  phylanx/plugins/keras_support/keras_support.hpp
  phylanx/plugins/keras_support/softmax_operation.hpp
  phylanx/plugins/matrixops/matrixops.hpp
  src/plugins/CMakeLists.txt
  src/plugins/keras_support/CMakeLists.txt
  src/plugins/keras_support/keras_support.cpp
  src/plugins/keras_support/softmax_operation.cpp
  src/plugins/matrixops/matrixops.cpp
  tests/unit/plugins/CMakeLists.txt
  tests/unit/plugins/keras_support/CMakeLists.txt
  tests/unit/plugins/keras_support/softmax_operation.cpp
  tests/unit/plugins/matrixops/CMakeLists.txt
Labels: category: primitives, type: compatibility issue, type: enhancement

#865 Adding truncated_normal random number distribution
  phylanx/include/util.hpp
  phylanx/plugins/matrixops/random.hpp
  phylanx/util/truncated_normal_distribution.hpp
  src/plugins/matrixops/random.cpp
  tests/unit/plugins/matrixops/random_distributions.cpp
Labels: category: primitives, type: enhancement

#867 Adding size primitive
  phylanx/plugins/matrixops/matrixops.hpp
  phylanx/plugins/matrixops/size.hpp
  src/plugins/matrixops/matrixops.cpp
  src/plugins/matrixops/size.cpp
  tests/unit/plugins/matrixops/CMakeLists.txt
  tests/unit/plugins/matrixops/size.cpp
Labels: category: primitives, type: compatibility issue, type: enhancement

#868 Fixing statistics primitive's handling of lists of axes
  phylanx/plugins/statistics/statistics_base.hpp
  phylanx/plugins/statistics/statistics_base_impl.hpp
  src/plugins/statistics/all_operation.cpp
  src/plugins/statistics/any_operation.cpp
  src/plugins/statistics/logsumexp_operation.cpp
  src/plugins/statistics/max_operation.cpp
  src/plugins/statistics/mean_operation.cpp
  src/plugins/statistics/min_operation.cpp
  src/plugins/statistics/prod_operation.cpp
  src/plugins/statistics/std_operation.cpp
  src/plugins/statistics/sum_operation.cpp
  src/plugins/statistics/var_operation.cpp
  tests/regressions/python/862_var_std_two_axis.py
  tests/regressions/python/CMakeLists.txt
  tests/unit/plugins/statistics/max_operation.cpp
  tests/unit/plugins/statistics/min_operation.cpp
Labels: category: primitives, type: compatibility issue, type: enhancement

#829 Enforce Python version.
  .gitignore
  cmake/Phylanx_SetupPybind11.cmake
  cmake/templates/__init__.py.in
Labels: submodule: frontend, type: enhancement

#869 Adding softplus() to Keras support plugin
  phylanx/ir/node_data.hpp
  phylanx/plugins/keras_support/keras_support.hpp
  phylanx/plugins/keras_support/softplus_operation.hpp
  src/ir/node_data.cpp
  src/plugins/keras_support/keras_support.cpp
  src/plugins/keras_support/softplus_operation.cpp
  tests/unit/plugins/keras_support/CMakeLists.txt
  tests/unit/plugins/keras_support/softplus_operation.cpp
Labels: category: primitives, platform: KERAS, type: compatibility issue, type: enhancement

#877 Adding batch_dot operation
  phylanx/plugins/keras_support/batch_dot_operation.hpp
  phylanx/plugins/keras_support/keras_support.hpp
  src/plugins/keras_support/batch_dot_operation.cpp
  src/plugins/keras_support/keras_support.cpp
  tests/unit/plugins/keras_support/CMakeLists.txt
  tests/unit/plugins/keras_support/batch_dot_operation.cpp
Labels: platform: KERAS, submodule: backend

#880 Modifying hard_sigmoid
  src/plugins/keras_support/hard_sigmoid_operation.cpp
  tests/unit/plugins/keras_support/hard_sigmoid_operation.cpp
Labels: platform: KERAS, submodule: backend, type: compatibility issue

#871 Adding one_hot operation
  phylanx/plugins/keras_support/keras_support.hpp
  phylanx/plugins/keras_support/one_hot_operation.hpp
  src/plugins/keras_support/keras_support.cpp
  src/plugins/keras_support/one_hot_operation.cpp
  tests/unit/plugins/keras_support/CMakeLists.txt
  tests/unit/plugins/keras_support/one_hot_operation.cpp
Labels: category: primitives, platform: KERAS, type: compatibility issue, type: enhancement

#882 Adding elu_operation primitive
  phylanx/plugins/keras_support/elu_operation.hpp
  phylanx/plugins/keras_support/keras_support.hpp
  src/plugins/keras_support/elu_operation.cpp
  src/plugins/keras_support/keras_support.cpp
  tests/unit/plugins/keras_support/CMakeLists.txt
  tests/unit/plugins/keras_support/elu_operation.cpp
Labels: category: primitives, type: compatibility issue, type: enhancement

#885 Using correct HPX registry variable name for PHYLANX_PLUGIN_PATH
  src/version.cpp
Labels: category: @Phylanx, type: compatibility issue, type: enhancement

#879 Completing the sections related to stack primitive in stack_operation
  phylanx/plugins/matrixops/stack_operation.hpp
  src/plugins/matrixops/concatenate.cpp
  src/plugins/matrixops/stack_operation.cpp
  tests/unit/plugins/matrixops/CMakeLists.txt
  tests/unit/plugins/matrixops/stack_operation.cpp
Labels: category: primitives, type: enhancement

#875 revisions (only) on openscop backend
  python/phylanx/ast/openscop.py
  python/phylanx/ast/oscop.py
  python/phylanx/ast/templates.py
  python/phylanx/ast/transducer.py
  python/phylanx/ast/utils.py
Labels: submodule: frontend, type: enhancement

#878 Fixing C++17 mode compilation for MSVC
  .circleci/config.yml
  cmake/Phylanx_DetectCppDialect.cmake
  cmake/Phylanx_SetupPybind11.cmake
  phylanx/util/variant.hpp
  src/plugins/matrixops/insert.cpp
Labels: compiler: msvc, type: compatibility issue, type: enhancement

#890 Fixing 'not None' to be properly evaluated
  phylanx/ast/node.hpp
  phylanx/plugins/booleans/logical_operation_impl.hpp
  src/plugins/booleans/unary_not_operation.cpp
  tests/regressions/python/886_notnone.py
  tests/regressions/python/CMakeLists.txt
  tests/unit/algorithm/CMakeLists.txt
Labels: category: @Phylanx, type: enhancement

#876 Adding support for the main cases for 2d/3d advanced slicing
  phylanx/execution_tree/primitives/detail/slice_assign.hpp
  phylanx/execution_tree/primitives/detail/slice_identity.hpp
  phylanx/execution_tree/primitives/slice_node_data_2d.hpp
  phylanx/execution_tree/primitives/slice_node_data_3d.hpp
  src/execution_tree/primitives/slice.cpp
  src/execution_tree/primitives/slice_node_data.cpp
  tests/unit/execution_tree/primitives/advanced_integer_slicing.cpp
  tests/unit/plugins/matrixops/slicing_operation.cpp
  tools/VS/blaze.natvis
Labels: category: primitives, type: compatibility issue, type: enhancement

#898 Properly handle numpy scalar types
  .circleci/config.yml
  python/src/bindings/type_casters.hpp
  tests/regressions/python/846_if_expression.py
  tests/regressions/python/874_0d_shape.py
  tests/regressions/python/CMakeLists.txt
Labels: category: @Phylanx, type: compatibility issue, type: enhancement

#899 Properly handle None in translation layer
  python/src/bindings/binding_helpers.cpp
  python/src/bindings/type_casters.hpp
  tests/regressions/python/896_return_none.py
  tests/regressions/python/CMakeLists.txt
Labels: category: @Phylanx, type: compatibility issue, type: enhancement

#881 Adding l2_normalize operation
  phylanx/plugins/keras_support/keras_support.hpp
  phylanx/plugins/keras_support/l2_normalize_operation.hpp
  src/plugins/keras_support/keras_support.cpp
  src/plugins/keras_support/l2_normalize_operation.cpp
  src/plugins/matrixops/transpose_operation.cpp
  tests/unit/plugins/keras_support/CMakeLists.txt
  tests/unit/plugins/keras_support/l2_normalize_operation.cpp
  tests/unit/plugins/matrixops/transpose_operation.cpp
Labels: platform: KERAS, submodule: backend

#870 Adding ReLU primitive
  phylanx/plugins/keras_support/keras_support.hpp
  phylanx/plugins/keras_support/relu_operation.hpp
  src/plugins/keras_support/keras_support.cpp
  src/plugins/keras_support/relu_operation.cpp
  tests/unit/plugins/keras_support/CMakeLists.txt
  tests/unit/plugins/keras_support/relu_operation.cpp
Labels: category: primitives, platform: KERAS, type: compatibility issue, type: enhancement

#897 Fix #815.
  python/phylanx/ast/physl.py
  tests/regressions/python/815_plain_return.py
  tests/regressions/python/CMakeLists.txt
Labels: category: @Phylanx, submodule: frontend, type: defect

#906 Tag stable builds and push them
  .circleci/config.yml
Labels: category: continuous integration, type: enhancement

#907 Only push the stable tag
  .circleci/config.yml
Labels: category: continuous integration, type: enhancement

#913 Adding missing pp guards for Blaze Tensor
  phylanx/execution_tree/primitives/detail/slice_assign.hpp
  phylanx/execution_tree/primitives/detail/slice_identity.hpp
Labels: type: compatibility issue, type: enhancement

#909 Adding execution_tree.variable to the Python bindings
  examples/InitMatrix.py
  phylanx/execution_tree/primitives/base_primitive.hpp
  python/src/bindings/binding_helpers.cpp
  python/src/bindings/binding_helpers.hpp
  python/src/bindings/execution_tree.cpp
  python/src/bindings/type_casters.hpp
  python/src/bindings/variable.cpp
  python/src/bindings/variable.hpp
  src/execution_tree/primitives/base_primitive.cpp
  src/ir/node_data.cpp
  tests/regressions/python/805_lazy_variable.py
  tests/regressions/python/805_two_variables.py
  tests/regressions/python/852_concatenate_list.py
  tests/regressions/python/874_0d_shape.py
  tests/regressions/python/903_variable_conversion.py
  tests/regressions/python/903_variable_dtype.py
  tests/regressions/python/CMakeLists.txt
  tests/unit/python/execution_tree/eval.py
  tests/unit/python/execution_tree/make_array.py
Labels: category: @Phylanx, compiler: python, submodule: backend, submodule: frontend, type: compatibility issue, type: enhancement
