Repository STEllAR-GROUP/phylanx, pull requests merged in 2019-05, with the labels that each got.

#973 Refactoring conv1D, extract index calculations
  phylanx/plugins/keras_support/conv1d_operation.hpp
  src/plugins/keras_support/conv1d_operation.cpp
Labels: category: primitives, type: enhancement

#976 Adding missing BlazeTensor conditionals
  src/plugins/keras_support/keras_support.cpp
  src/plugins/matrixops/stack_operation.cpp
Labels: type: compatibility issue

#971 Modifying l2_normalize
  src/plugins/keras_support/l2_normalize_operation.cpp
  tests/unit/plugins/keras_support/l2_normalize_operation.cpp
Labels: category: primitives, type: enhancement

#984 Adding extract_scalar_positive_integer_value to base primitive
  phylanx/execution_tree/primitives/base_primitive.hpp
  src/execution_tree/primitives/base_primitive.cpp
Labels: category: PhySL, type: enhancement

#982 Bring in K-means fix from eval_move branch
  examples/algorithms/CMakeLists.txt
  examples/algorithms/kmeans/kmeans.cpp
  examples/algorithms/kmeans/kmeans.physl
Labels: category: PhySL, category: examples, type: enhancement

#981 Support lazy compilation.
  python/phylanx/ast/physl.py
  tests/regressions/python/979_lazy_compilation.py
  tests/regressions/python/979_lazy_compilation_with_init.py
  tests/regressions/python/CMakeLists.txt
Labels: category: @Phylanx, submodule: frontend

#970 improve expression parsing; add support for multidimensional array
  python/phylanx/ast/openscop.py
Labels: submodule: frontend, type: enhancement

#986 Doc updates
  cmake/Phylanx_CreateSymbolicLink.cmake
  cmake/scripts/create_symbolic_link_directory.bat
  cmake/scripts/create_symbolic_link_file.bat
  cmake/templates/generate_rst.py.in
  docs/CMakeLists.txt
  docs/sphinx/acknowledgement.rst
  docs/sphinx/manual.rst
  docs/sphinx/manual/about.rst
  docs/sphinx/manual/images/phylanx_overview.png
  docs/sphinx/manual/software_stack.rst
Labels: category: documentation
