Repository STEllAR-GROUP/phylanx, pull requests merged in 2019-01, with the labels that each got.

#717 Get rid of all references to LIB and replace them with CMAKE_INSTALL_LIBDIR
  CMakeLists.txt
  cmake/Phylanx_GeneratePackage.cmake
  cmake/templates/PhylanxConfig.cmake.in
Labels: category: CMake, type: compatibility issue, type: enhancement

#719 Add astpretty to the CircleCI base image
  tools/docker/base/Dockerfile
Labels: category: continuous integration

#701 Adding Flip primitive
  phylanx/plugins/matrixops/flip_operation.hpp
  phylanx/plugins/matrixops/matrixops.hpp
  phylanx/util/detail/bad_swap.hpp
  src/plugins/matrixops/flip_operation.cpp
  src/plugins/matrixops/matrixops.cpp
  src/plugins/matrixops/shuffle_operation.cpp
  tests/unit/plugins/matrixops/CMakeLists.txt
  tests/unit/plugins/matrixops/flip_operation.cpp
Labels: category: primitives, submodule: backend, type: enhancement

#723 Adding the environment variable `PHYLANX_PLUGINS_PATH`
  phylanx/execution_tree/primitives/primitive_component_base.hpp
  phylanx/plugins/plugin_base.hpp
  phylanx/plugins/plugin_factory.hpp
  src/execution_tree/patterns.cpp
  src/plugins/arithmetics/arithmetics.cpp
  src/plugins/listops/listops.cpp
  src/plugins/load_plugins.cpp
  src/plugins/solvers/solvers.cpp
  src/version.cpp
  tests/unit/distributed/remote_run.cpp
Labels: category: primitives, submodule: backend, type: compatibility issue, type: enhancement

#679 Vsplit
  phylanx/plugins/matrixops/matrixops.hpp
  phylanx/plugins/matrixops/vsplit_operation.hpp
  src/plugins/matrixops/matrixops.cpp
  src/plugins/matrixops/vsplit_operation.cpp
  tests/unit/plugins/matrixops/CMakeLists.txt
  tests/unit/plugins/matrixops/vsplit_operation.cpp
Labels: category: primitives

#721 Adding support for integer arrays to PhySL parser
  phylanx/ast/match_ast.hpp
  phylanx/ast/node.hpp
  phylanx/ast/parser/ast.hpp
  phylanx/ast/parser/expression.hpp
  phylanx/ast/parser/expression_def.hpp
  phylanx/ast/traverse.hpp
  src/ast/detail/is_literal_value.cpp
  src/ast/generate_ast.cpp
  src/ast/transform_ast.cpp
  src/execution_tree/primitives/base_primitive.cpp
  tests/regressions/ast/720_parse_arrays.cpp
  tests/regressions/ast/CMakeLists.txt
  tests/unit/ast/generate_ast.cpp
  tests/unit/plugins/solvers/decomposition.cpp
Labels: category: PhySL, submodule: backend, type: compatibility issue, type: enhancement

#699 Adding various numeric numpy constants
  python/phylanx/ast/physl.py
  src/execution_tree/compiler/compiler.cpp
  tests/unit/python/execution_tree/CMakeLists.txt
  tests/unit/python/execution_tree/map_numpy_constants.py
Labels: category: PhySL, submodule: backend, type: compatibility issue

#714 Attempting to improve CircleCI workflow
  .circleci/config.yml
Labels: category: continuous integration, type: enhancement

#732 Fix incorrect repository name in documentation
  cmake/Phylanx_UpdateGitDocs.cmake
Labels: category: documentation, type: enhancement

#731 Adding Clip primitive
  phylanx/plugins/matrixops/clip.hpp
  phylanx/plugins/matrixops/matrixops.hpp
  phylanx/util/detail/numeric_limits_min.hpp
  src/plugins/matrixops/argmax.cpp
  src/plugins/matrixops/clip.cpp
  src/plugins/matrixops/matrixops.cpp
  src/plugins/statistics/max_operation.cpp
  tests/unit/plugins/matrixops/CMakeLists.txt
  tests/unit/plugins/matrixops/clip.cpp
Labels: category: primitives, type: enhancement

#730 Adding ndim primitive
  phylanx/plugins/matrixops/matrixops.hpp
  phylanx/plugins/matrixops/ndim.hpp
  src/plugins/matrixops/matrixops.cpp
  src/plugins/matrixops/ndim.cpp
  tests/unit/plugins/matrixops/CMakeLists.txt
  tests/unit/plugins/matrixops/ndim.cpp
Labels: category: primitives, type: enhancement

#728 Modifying expand dims and tile primitives
  phylanx/plugins/matrixops/expand_dims.hpp
  src/plugins/matrixops/expand_dims.cpp
  src/plugins/matrixops/tile_operation.cpp
  tests/unit/plugins/matrixops/expand_dims.cpp
Labels: submodule: backend, type: compatibility issue, type: defect

#745 Adding tensor iterators
  phylanx/util/tensor_iterators.hpp
Labels: category: primitives, submodule: backend, type: compatibility issue, type: enhancement

#740 Modifying transpose operation to accept `axes`
  phylanx/plugins/matrixops/transpose_operation.hpp
  src/plugins/matrixops/transpose_operation.cpp
  tests/unit/plugins/matrixops/transpose_operation.cpp
Labels: category: primitives, submodule: backend, type: enhancement

#742 Adding 3D support for tile operation
  phylanx/plugins/matrixops/tile_operation.hpp
  src/plugins/matrixops/tile_operation.cpp
  tests/unit/plugins/matrixops/tile_operation.cpp
Labels: submodule: backend, type: enhancement

#744 Automatic Documentation Push
  .circleci/config.yml
  cmake/Phylanx_Documentation.cmake
  cmake/templates/conf.py.in
Labels: category: continuous integration, category: documentation, type: enhancement

#736 update neural network codes for different versions
  examples/algorithms/nn/CMakeLists.txt
  examples/algorithms/nn/nn.py
  examples/algorithms/nn/nn_csv.cpp
  examples/algorithms/nn/nn_csv_numpy.py
  examples/algorithms/nn/nn_csv_phylanx.physl
  examples/algorithms/nn/nn_csv_phylanx.py
Labels: category: algorithms, category: examples

#739 Update MPark's variant implementation
  phylanx/util/detail/variant.hpp
Labels: submodule: backend, type: enhancement

#747 Adding 3D support for repeat operation
  phylanx/plugins/matrixops/repeat_operation.hpp
  src/plugins/matrixops/repeat_operation.cpp
  tests/unit/plugins/matrixops/repeat_operation.cpp
Labels: submodule: backend, type: enhancement

#749 Adding 3D support to the random primitive
  phylanx/plugins/matrixops/random.hpp
  src/plugins/matrixops/random.cpp
  tests/unit/plugins/matrixops/random_distributions.cpp
Labels: category: primitives, type: compatibility issue, type: enhancement

#750 Adding 3D support to the constant/constant_like primitives
  phylanx/plugins/matrixops/constant.hpp
  src/plugins/matrixops/constant.cpp
  tests/unit/plugins/matrixops/constant.cpp
Labels: category: primitives, type: compatibility issue, type: enhancement

#751 Adding 3D support to the argmin and argmax primitives
  phylanx/plugins/matrixops/argmax.hpp
  phylanx/plugins/matrixops/argmin.hpp
  phylanx/plugins/matrixops/argminmax.hpp
  phylanx/plugins/matrixops/argminmax_impl.hpp
  src/plugins/matrixops/argmax.cpp
  src/plugins/matrixops/argmin.cpp
  tests/unit/execution_tree/compiler.cpp
  tests/unit/plugins/matrixops/argmax.cpp
  tests/unit/plugins/matrixops/argmin.cpp
Labels: category: primitives, type: compatibility issue, type: enhancement

#756 Preparing build system to be usable for external plugin
  cmake/Phylanx_AddPrimitivePlugin.cmake
  cmake/Phylanx_GeneratePackage.cmake
  cmake/Phylanx_SetLibName.cmake
  cmake/templates/PhylanxConfig.cmake.in
Labels: category: CMake, type: compatibility issue, type: enhancement

#757 Adding 3D support for the flip operation
  phylanx/plugins/matrixops/flip_operation.hpp
  src/plugins/matrixops/flip_operation.cpp
  tests/unit/plugins/matrixops/flip_operation.cpp
Labels: category: primitives, submodule: backend, type: enhancement

#760 Adding 3D support for the dot operation
  phylanx/plugins/matrixops/dot_operation.hpp
  src/plugins/matrixops/dot_operation.cpp
  tests/unit/plugins/matrixops/dot_operation.cpp
Labels: category: primitives, submodule: backend, type: enhancement

#762 Have ninja explain why it rebuild targets
  .circleci/config.yml
Labels: category: continuous integration

#765 Fix CMake reruns on CircleCI
  .circleci/config.yml
Labels: category: continuous integration
