Repository STEllAR-GROUP/phylanx, pull requests merged in 2019-07, with the labels that each got.

#995 Adding apex task inlining policy
  CMakeLists.txt
  phylanx/execution_tree/primitives/primitive_component_base.hpp
  phylanx/util/apex_task_inlining_policy.hpp
  src/execution_tree/primitives/primitive_component.cpp
  src/execution_tree/primitives/primitive_component_base.cpp
Labels: category: primitives, type: enhancement

#998 Fixing bug on indices helpers
  phylanx/plugins/keras_support/conv_indices_helper.hpp
  phylanx/plugins/keras_support/pool_indices_helper.hpp
  src/plugins/keras_support/avg_pool2d_operation.cpp
  src/plugins/keras_support/avg_pool3d_operation.cpp
  src/plugins/keras_support/conv1d_operation.cpp
  src/plugins/keras_support/max_pool2d_operation.cpp
  src/plugins/keras_support/max_pool3d_operation.cpp
  src/plugins/keras_support/separable_conv1d_operation.cpp
Labels: type: defect

#989 Adding docs
  docs/sphinx/manual.rst
  docs/sphinx/manual/about.rst
  docs/sphinx/manual/lra_example.rst
  docs/sphinx/manual/software_stack.rst
Labels: category: documentation

#1000 Disable HIGHFIVE_UNIT_TESTS in the base image
  tools/docker/base/Dockerfile
Labels: category: continuous integration

#996 Adapting to recent #include changes in HPX
  phylanx/ast/match_ast.hpp
  phylanx/execution_tree/compiler/actors.hpp
  phylanx/execution_tree/primitives/primitive_argument_type.hpp
  phylanx/execution_tree/primitives/python_gil_hook.hpp
  phylanx/execution_tree/primitives/slice_node_data_1d.hpp
  phylanx/execution_tree/primitives/slice_node_data_2d.hpp
  phylanx/execution_tree/primitives/slice_node_data_3d.hpp
  phylanx/plugins/arithmetics/generic_operation_0d.hpp
  phylanx/plugins/arithmetics/generic_operation_1d.hpp
  phylanx/plugins/arithmetics/generic_operation_2d.hpp
  phylanx/plugins/arithmetics/generic_operation_3d.hpp
  phylanx/plugins/arithmetics/generic_operation_bool_nd.hpp
  phylanx/plugins/statistics/statistics_base_impl.hpp
  phylanx/util/distributed_object.hpp
  phylanx/util/truncated_normal_distribution.hpp
  python/src/bindings/type_casters.hpp
  python/src/bindings/variable.cpp
  src/execution_tree/primitives/access_argument.cpp
  src/execution_tree/primitives/define_variable.cpp
  src/execution_tree/primitives/lambda.cpp
  src/execution_tree/primitives/node_data_helpers0d.cpp
  src/execution_tree/primitives/slice.cpp
  src/execution_tree/primitives/slice_node_data.cpp
  src/execution_tree/primitives/slice_range.cpp
  src/execution_tree/primitives/store_operation.cpp
  src/plugins/arithmetics/generic_operation.cpp
  src/plugins/arithmetics/generic_operation_bool.cpp
  src/plugins/booleans/nonzero_where.cpp
  src/plugins/controls/apply.cpp
  src/plugins/controls/fmap_operation.cpp
  src/plugins/keras_support/binary_crossentropy_operation.cpp
  src/plugins/keras_support/categorical_crossentropy_operation.cpp
  src/plugins/listops/car_cdr_operation.cpp
  src/plugins/matrixops/constant.cpp
  src/plugins/matrixops/random.cpp
  src/plugins/matrixops/slicing_operation.cpp
  src/plugins/solvers/decomposition.cpp
  src/plugins/solvers/linear_solver.cpp
  src/plugins/statistics/std_operation.cpp
  src/plugins/statistics/var_operation.cpp
  src/util/performance_data.cpp
  src/util/slicing_helpers.cpp
  tools/inspect/include_check.cpp
Labels: type: compatibility issue, type: enhancement

#1002 Adjusting for HPX format module include changes
  phylanx/execution_tree/primitives/slice_node_data_1d.hpp
  phylanx/plugins/arithmetics/cumulative_impl.hpp
  python/src/bindings/variable.cpp
  src/util/generate_error_message.cpp
  src/version.cpp
  tests/unit/distributed/define_locality.cpp
  tests/unit/execution_tree/define_locality.cpp
  tools/inspect/deprecated_include_check.cpp
Labels: type: compatibility issue, type: enhancement

#1005 Fix help
  src/plugins/controls/fold_left_operation.cpp
  src/plugins/controls/fold_right_operation.cpp
  src/plugins/keras_support/batch_dot_operation.cpp
  src/plugins/keras_support/ctc_decode_operation.cpp
  src/plugins/matrixops/argsort.cpp
  tools/check_help/check_help.py
Labels: category: @Phylanx

#1008 Adjust for new HPX modules
  phylanx/ast/match_ast.hpp
  phylanx/ast/traverse.hpp
  phylanx/execution_tree/primitives/primitive_argument_type.hpp
  phylanx/execution_tree/primitives/primitive_component_base.hpp
  phylanx/ir/ranges.hpp
  phylanx/plugins/arithmetics/cumulative.hpp
  phylanx/plugins/arithmetics/cumulative_impl.hpp
  phylanx/plugins/keras_support/avg_pool2d_operation.hpp
  phylanx/plugins/keras_support/avg_pool3d_operation.hpp
  phylanx/plugins/keras_support/conv1d_operation.hpp
  phylanx/plugins/keras_support/max_pool2d_operation.hpp
  phylanx/plugins/keras_support/max_pool3d_operation.hpp
  phylanx/plugins/keras_support/separable_conv1d_operation.hpp
  phylanx/plugins/matrixops/argminmax_impl.hpp
  phylanx/plugins/matrixops/flip_operation.hpp
  phylanx/plugins/matrixops/insert.hpp
  phylanx/plugins/matrixops/repeat_operation.hpp
  phylanx/plugins/matrixops/squeeze_operation.hpp
  phylanx/plugins/plugin_factory_base.hpp
  phylanx/plugins/statistics/statistics_base.hpp
  phylanx/plugins/statistics/statistics_base_impl.hpp
  phylanx/util/distributed_object.hpp
  phylanx/util/hashed_string.hpp
  phylanx/util/matrix_iterators.hpp
  phylanx/util/scoped_timer.hpp
  phylanx/util/tensor_iterators.hpp
  python/src/bindings/type_casters.hpp
  src/execution_tree/primitives/base_primitive.cpp
  src/execution_tree/primitives/function.cpp
  src/execution_tree/primitives/primitive_argument_type.cpp
  src/execution_tree/primitives/variable.cpp
  src/plugins/keras_support/avg_pool2d_operation.cpp
  src/plugins/keras_support/avg_pool3d_operation.cpp
  src/plugins/keras_support/conv1d_operation.cpp
  src/plugins/keras_support/max_pool2d_operation.cpp
  src/plugins/keras_support/max_pool3d_operation.cpp
  src/plugins/keras_support/relu_operation.cpp
  src/plugins/keras_support/separable_conv1d_operation.cpp
  src/plugins/matrixops/clip.cpp
  src/plugins/matrixops/concatenate.cpp
  src/plugins/matrixops/expand_dims.cpp
  src/plugins/matrixops/flip_operation.cpp
  src/plugins/matrixops/insert.cpp
  src/plugins/matrixops/pad.cpp
  src/plugins/matrixops/repeat_operation.cpp
  src/plugins/matrixops/reshape_operation.cpp
  src/plugins/matrixops/sort.cpp
  src/plugins/matrixops/squeeze_operation.cpp
  src/plugins/matrixops/tile_operation.cpp
  src/plugins/matrixops/unique.cpp
  src/plugins/statistics/logsumexp_operation.cpp
Labels: type: compatibility issue, type: enhancement
