Repository STEllAR-GROUP/phylanx, pull requests merged in 2019-10, with the labels that each got.

#1043 Adding 4D support to squeeze operation
  phylanx/plugins/matrixops/squeeze_operation.hpp
  src/plugins/matrixops/squeeze_operation.cpp
  tests/unit/plugins/matrixops/squeeze_operation.cpp
Labels: submodule: backend, type: enhancement

#1042 Adding conv2d operation
  phylanx/plugins/keras_support/conv2d_operation.hpp
  phylanx/plugins/keras_support/keras_support.hpp
  src/plugins/keras_support/conv2d_operation.cpp
  src/plugins/keras_support/keras_support.cpp
  tests/unit/plugins/keras_support/CMakeLists.txt
  tests/unit/plugins/keras_support/conv2d_operation.cpp
Labels: category: primitives, platform: KERAS, submodule: backend

#1045 Preconditioned cg
  src/plugins/solvers/linear_solver.cpp
  tests/unit/plugins/solvers/linear_solver.cpp
Labels: category: tests

#1049 Fixing serialization problems introduced by recent HPX changes
  phylanx/ast/node.hpp
  phylanx/execution_tree/annotation.hpp
  phylanx/execution_tree/compiler/actors.hpp
  phylanx/execution_tree/primitives/primitive_argument_type.hpp
  phylanx/ir/dictionary.hpp
  phylanx/ir/node_data.hpp
  phylanx/ir/ranges.hpp
  phylanx/util/hashed_string.hpp
  phylanx/util/serialization/blaze.hpp
  phylanx/util/serialization/variant.hpp
  src/execution_tree/annotation.cpp
Labels: type: compatibility issue, type: enhancement

#1048 Adding 4D support to the softmax operation
  phylanx/plugins/keras_support/softmax_operation.hpp
  src/plugins/keras_support/softmax_operation.cpp
  tests/unit/plugins/keras_support/softmax_operation.cpp
Labels: category: primitives, platform: KERAS, submodule: backend

#1051 Adding Conv2d_transpose operation
  phylanx/plugins/keras_support/conv2d_transpose_operation.hpp
  phylanx/plugins/keras_support/conv_indices_helper.hpp
  phylanx/plugins/keras_support/keras_support.hpp
  src/plugins/keras_support/conv2d_operation.cpp
  src/plugins/keras_support/conv2d_transpose_operation.cpp
  src/plugins/keras_support/keras_support.cpp
  tests/unit/plugins/keras_support/CMakeLists.txt
  tests/unit/plugins/keras_support/conv2d_transpose_operation.cpp
Labels: category: primitives, platform: KERAS, submodule: backend

#1041 Avoid redundant compilations.
  python/phylanx/ast/physl.py
Labels: category: @Phylanx, submodule: frontend, type: defect

#1046 Test dot 2d2d
  phylanx/execution_tree/annotation.hpp
  phylanx/execution_tree/primitives/primitive_argument_type.hpp
  phylanx/plugins/dist_matrixops/dist_dot_operation.hpp
  phylanx/plugins/dist_matrixops/dist_dot_operation_impl.hpp
  phylanx/util/distributed_matrix.hpp
  src/execution_tree/annotation.cpp
  src/execution_tree/localities_annotation.cpp
  src/execution_tree/primitives/base_primitive.cpp
  src/execution_tree/primitives/primitive_argument_type.cpp
  src/plugins/dist_matrixops/dist_dot_operation.cpp
  src/plugins/support_components.cpp
  tests/unit/execution_tree/CMakeLists.txt
  tests/unit/execution_tree/annotation.cpp
  tests/unit/plugins/dist_matrixops/dist_dot_operation.cpp
  tools/VS/blaze.natvis
Labels: type: enhancement

#1050 Add Lanczos solver
  phylanx/plugins/solvers/linear_solver.hpp
  src/plugins/solvers/linear_solver.cpp
  tests/unit/plugins/solvers/linear_solver.cpp
Labels: category: algorithms

#1055 Adding variable._keras_shape attribute
  python/src/bindings/binding_helpers.cpp
  python/src/bindings/binding_helpers.hpp
  python/src/bindings/execution_tree.cpp
  python/src/bindings/variable.cpp
  python/src/bindings/variable.hpp
  tests/regressions/python/1054_variable_shape.py
  tests/regressions/python/CMakeLists.txt
Labels: platform: KERAS, submodule: frontend, type: compatibility issue, type: enhancement

#1053 Allowing to assign to variable.dtype
  python/src/bindings/execution_tree.cpp
  python/src/bindings/variable.cpp
  python/src/bindings/variable.hpp
  tests/regressions/python/1052_variable_set_dtype.py
  tests/regressions/python/CMakeLists.txt
Labels: submodule: frontend, type: compatibility issue, type: enhancement

#1057 Making sure execution_tree::primitive attached to Python object is not moved away during translation
  python/src/bindings/type_casters.hpp
  tests/regressions/python/1056_client_base.py
  tests/regressions/python/CMakeLists.txt
Labels: category: @Phylanx, submodule: frontend, type: enhancement

#1058 Enabling simplified definition of lazy functions
  .clang-format
  python/phylanx/ast/transducer.py
  python/phylanx/exceptions.py
  src/plugins/controls/fmap_operation.cpp
  tests/regressions/python/942_lazy_fmap.py
  tests/regressions/python/CMakeLists.txt
Labels: category: @Phylanx, type: compatibility issue, type: enhancement

#1062 Exclude HighFive examples from building in the base image
  .circleci/config.yml
  tools/docker/base/Dockerfile
Labels: category: continuous integration, type: enhancement
