Repository STEllAR-GROUP/phylanx, pull requests merged in 2019-11, with the labels that each got.

#1060 Add arnoldi solver
  src/plugins/solvers/linear_solver.cpp
  tests/unit/plugins/solvers/linear_solver.cpp
Labels: category: algorithms

#1073 Re-adding compatibility checks with HPX build system
  CMakeLists.txt
  cmake/Phylanx_SetupHPX.cmake
  cmake/Phylanx_Utils.cmake
Labels: category: CMake, type: compatibility issue, type: enhancement

#1075 Making variable changes compatible with pybind 2.2.3-1
  python/src/bindings/variable.cpp
Labels: type: compatibility issue

#1076 Add GMRES and remove trans() when passing A
  src/plugins/solvers/linear_solver.cpp
  tests/unit/plugins/solvers/linear_solver.cpp
Labels: category: algorithms

#1074 Storing generated PhySL string and AST in database
  cmake/Phylanx_SetupHPX.cmake
  python/phylanx/ast/physl.py
  python/phylanx/ast/physl_db.py
  python/phylanx/ast/transducer.py
  python/src/bindings/binding_helpers.cpp
  python/src/bindings/binding_helpers.hpp
  python/src/bindings/execution_tree.cpp
  tests/regressions/python/640_function_argument.py
  tests/regressions/python/create_list_409.py
  tests/regressions/python/name_constants_411.py
  tests/unit/python/execution_tree/map_numpy.py
  tests/unit/python/execution_tree/multi_return.py
Labels: category: @Phylanx, type: enhancement
