Repository STEllAR-GROUP/phylanx, pull requests merged in 2019-02, with the labels that each got.

#764 Adding flipud and fliplr to the flip operation
  phylanx/plugins/matrixops/flip_operation.hpp
  src/plugins/matrixops/flip_operation.cpp
  src/plugins/matrixops/matrixops.cpp
  tests/unit/plugins/matrixops/flip_operation.cpp
Labels: category: primitives, submodule: backend

#772 Moving definition from source to header.
  phylanx/execution_tree/primitives/node_data_helpers.hpp
  src/execution_tree/primitives/node_data_helpers0d.cpp
Labels: category: primitives, compiler: gcc, type: enhancement

#773 Updating softmax based on blaze::softmax updates
  src/plugins/matrixops/softmax_operation.cpp
Labels: category: primitives, submodule: backend, type: enhancement

#763 Adding concatenate primitive
  phylanx/plugins/matrixops/concatenate.hpp
  phylanx/plugins/matrixops/matrixops.hpp
  src/plugins/matrixops/concatenate.cpp
  src/plugins/matrixops/matrixops.cpp
  tests/unit/plugins/matrixops/CMakeLists.txt
  tests/unit/plugins/matrixops/concatenate.cpp
Labels: category: primitives, type: compatibility issue, type: enhancement

#780 Avoiding creating the unneeded copy in concatenate primitive
  src/plugins/matrixops/concatenate.cpp
Labels: category: primitives, type: enhancement

#781 Adding 3D support for the squeeze primitive
  phylanx/plugins/matrixops/squeeze_operation.hpp
  src/plugins/matrixops/squeeze_operation.cpp
  tests/unit/plugins/matrixops/squeeze_operation.cpp
Labels: category: primitives, submodule: backend, type: enhancement

#783 Adding Tensordot primitive
  phylanx/plugins/matrixops/dot_operation.hpp
  phylanx/plugins/matrixops/dot_operation_impl.hpp
  src/plugins/matrixops/dot_operation.cpp
  src/plugins/matrixops/dot_operation_double.cpp
  src/plugins/matrixops/dot_operation_int64.cpp
  src/plugins/matrixops/dot_operation_uint8.cpp
  src/plugins/matrixops/matrixops.cpp
  tests/unit/plugins/matrixops/dot_operation.cpp
Labels: category: primitives, submodule: backend

#785 Updating tensordot in its usage of blaze::ravel
  phylanx/plugins/matrixops/dot_operation_impl.hpp
  tests/unit/plugins/matrixops/dot_operation.cpp
Labels: category: primitives, type: compatibility issue

#784 Add symbol table infrastructure.
  python/phylanx/ir/__init__.py
  python/phylanx/ir/nodes.py
  python/phylanx/ir/symbol_table.py
  tests/unit/python/ir/test_nodes.py
  tests/unit/python/ir/test_symbol_table.py
Labels: category: @Phylanx, submodule: frontend, type: enhancement

#787 Adding 3d support to the transpose operation
  phylanx/plugins/matrixops/transpose_operation.hpp
  src/plugins/matrixops/transpose_operation.cpp
  tests/unit/plugins/matrixops/transpose_operation.cpp
Labels: submodule: backend, type: enhancement

#786 PHYSL_IR environment variable
  examples/interpreter/physl.cpp
Labels: category: PhySL, submodule: backend

#782 Adding insert primitive
  phylanx/plugins/matrixops/insert.hpp
  phylanx/plugins/matrixops/matrixops.hpp
  src/plugins/matrixops/insert.cpp
  src/plugins/matrixops/matrixops.cpp
  tests/unit/plugins/matrixops/CMakeLists.txt
  tests/unit/plugins/matrixops/insert.cpp
Labels: category: primitives, type: compatibility issue, type: enhancement

#790 Add sign and square to support the Keras backend.
  phylanx/plugins/arithmetics/generic_operation_0d.hpp
  phylanx/plugins/arithmetics/generic_operation_1d.hpp
  phylanx/plugins/arithmetics/generic_operation_2d.hpp
  phylanx/plugins/arithmetics/generic_operation_3d.hpp
  python/phylanx/ast/physl.py
  src/plugins/arithmetics/generic_operation.cpp
  tests/unit/plugins/arithmetics/generic_operation.cpp
  tests/unit/python/execution_tree/eval.py
Labels: category: primitives, type: compatibility issue, type: enhancement

#799 Adding insert primitive for cases where axis is not None
  phylanx/plugins/matrixops/insert.hpp
  src/plugins/matrixops/insert.cpp
  tests/unit/plugins/matrixops/insert.cpp
Labels: category: primitives, type: compatibility issue, type: enhancement

#797 Making sure [hvd]stack() can be called with a range.
  src/plugins/matrixops/stack_operation.cpp
  tests/regressions/execution_tree/792_hstack_range.cpp
  tests/regressions/execution_tree/CMakeLists.txt
Labels: category: primitives, type: enhancement

#788 Add missing constructors for 'var' to Python binders
  python/src/bindings/execution_tree.cpp
  python/src/bindings/util.cpp
Labels: compiler: python, submodule: middleware, type: compatibility issue, type: enhancement

#793 Added explicit braces to avoid dangling else in insert primitive
  src/plugins/matrixops/insert.cpp
Labels: category: primitives, platform: Mac OSX, type: compatibility issue, type: enhancement

#768 Adding pad primitive
  phylanx/plugins/matrixops/matrixops.hpp
  phylanx/plugins/matrixops/pad.hpp
  src/plugins/matrixops/matrixops.cpp
  src/plugins/matrixops/pad.cpp
  tests/unit/plugins/matrixops/CMakeLists.txt
  tests/unit/plugins/matrixops/pad.cpp
Labels: category: primitives, type: enhancement

#800 Frontend: Add 3d tensor support.
  python/phylanx/ast/physl.py
  tests/regressions/python/794_3d_array.py
  tests/regressions/python/CMakeLists.txt
Labels: category: @Phylanx, submodule: frontend, type: defect, type: regression

#813 Adding the missing ifdef for blaze tensor in insert primitive
  tests/unit/plugins/matrixops/insert.cpp
Labels: category: primitives, type: enhancement
