Repository STEllAR-GROUP/phylanx, pull requests merged in 2019-06, with the labels that each got.

#990 Adding simplified distributed object to Phylanx
  phylanx/include/util.hpp
  phylanx/util/distributed_object.hpp
  tests/unit/util/CMakeLists.txt
  tests/unit/util/distributed_object.cpp
Labels: category: PhySL, submodule: backend, type: enhancement

#991 Updating conv1d operation
  phylanx/plugins/keras_support/conv1d_operation.hpp
  phylanx/plugins/keras_support/conv_indices_helper.hpp
  src/plugins/keras_support/conv1d_operation.cpp
  src/plugins/keras_support/keras_support.cpp
  tests/unit/plugins/keras_support/conv1d_operation.cpp
Labels: type: enhancement

#993 Adding separable conv1d operation
  phylanx/plugins/keras_support/keras_support.hpp
  phylanx/plugins/keras_support/separable_conv1d_operation.hpp
  src/plugins/keras_support/keras_support.cpp
  src/plugins/keras_support/separable_conv1d_operation.cpp
  tests/unit/plugins/keras_support/CMakeLists.txt
  tests/unit/plugins/keras_support/separable_conv1d_operation.cpp
Labels: category: primitives, platform: KERAS, submodule: backend

#992 Updating pool operation
  phylanx/plugins/keras_support/avg_pool2d_operation.hpp
  phylanx/plugins/keras_support/avg_pool3d_operation.hpp
  phylanx/plugins/keras_support/keras_support.hpp
  phylanx/plugins/keras_support/max_pool2d_operation.hpp
  phylanx/plugins/keras_support/max_pool3d_operation.hpp
  phylanx/plugins/keras_support/pool_indices_helper.hpp
  phylanx/plugins/keras_support/pool_operation.hpp
  src/plugins/keras_support/avg_pool2d_operation.cpp
  src/plugins/keras_support/avg_pool3d_operation.cpp
  src/plugins/keras_support/keras_support.cpp
  src/plugins/keras_support/max_pool2d_operation.cpp
  src/plugins/keras_support/max_pool3d_operation.cpp
  src/plugins/keras_support/pool_operation.cpp
  tests/unit/plugins/keras_support/CMakeLists.txt
  tests/unit/plugins/keras_support/avg_pool2d_operation.cpp
  tests/unit/plugins/keras_support/avg_pool3d_operation.cpp
  tests/unit/plugins/keras_support/max_pool2d_operation.cpp
  tests/unit/plugins/keras_support/max_pool3d_operation.cpp
  tests/unit/plugins/keras_support/pool_operation.cpp
Labels: type: enhancement
