Repository STEllAR-GROUP/phylanx, pull requests merged in 2020-02, with the labels that each got.

#1094 Adding distributed dot1d2d
  phylanx/plugins/dist_matrixops/dist_dot_operation.hpp
  phylanx/plugins/dist_matrixops/dist_dot_operation_impl.hpp
  src/plugins/dist_matrixops/dist_dot_operation.cpp
  src/plugins/dist_matrixops/dist_dot_operation_double.cpp
  src/plugins/dist_matrixops/dist_dot_operation_int64.cpp
  src/plugins/dist_matrixops/dist_dot_operation_uint8.cpp
  tests/unit/plugins/dist_matrixops/dist_dot_operation.cpp
Labels: category: primitives, type: enhancement

#1100 Making sure counter names for distributed runs are properly handled
  examples/algorithms/lra/lra_csv_instrumented.cpp
  src/performance_counters/register_counters.cpp
  src/util/performance_data.cpp
  tests/unit/execution_tree/instrumentation.cpp
Labels: category: PhySL, type: compatibility issue, type: enhancement

#1099 Ignoring fake nil argument for function calls without args
  src/execution_tree/primitives/call_function.cpp
Labels: category: PhySL, type: compatibility issue, type: enhancement

#1103 Making sure primitive names are consistent for non-distributed runs
  .circleci/config.yml
  phylanx/execution_tree/compiler/primitive_name.hpp
  phylanx/util/future_or_value.hpp
  src/execution_tree/compiler/compiler.cpp
  src/plugins/fileio/file_read_csv.cpp
  src/plugins/fileio/file_write_csv.cpp
  tests/regressions/execution_tree/expression_topology_213.cpp
  tests/unit/execution_tree/expression_topology.cpp
  tests/unit/performance_counters/primitive_counter.cpp
  tests/unit/plugins/dist_matrixops/CMakeLists.txt
  tests/unit/util/performance_data.cpp
  tools/inspect/ascii_check.cpp
  tools/inspect/assert_macro_check.cpp
  tools/inspect/crlf_check.cpp
  tools/inspect/deprecated_include_check.cpp
  tools/inspect/deprecated_macro_check.cpp
  tools/inspect/deprecated_name_check.cpp
  tools/inspect/end_check.cpp
  tools/inspect/function_hyper.hpp
  tools/inspect/include_check.cpp
  tools/inspect/inspect.cpp
  tools/inspect/inspector.hpp
  tools/inspect/length_check.cpp
  tools/inspect/license_check.cpp
  tools/inspect/link_check.cpp
  tools/inspect/minmax_check.cpp
  tools/inspect/path_name_check.cpp
  tools/inspect/unnamed_namespace_check.cpp
Labels: category: PhySL, type: compatibility issue, type: enhancement

#1108 Fix string output
  python/phylanx/ast/physl.py
Labels: category: @Phylanx, type: compatibility issue, type: enhancement

#1110 Modifying Cannon product
  phylanx/plugins/dist_matrixops/dist_cannon_product_impl.hpp
  src/plugins/dist_matrixops/dist_cannon_product.cpp
  src/plugins/dist_matrixops/dist_dot_operation.cpp
  tests/unit/plugins/dist_matrixops/CMakeLists.txt
  tests/unit/plugins/dist_matrixops/dist_cannon_product.cpp
  tests/unit/plugins/dist_matrixops/dist_cannon_product_9_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_dot_operation.cpp
Labels: type: enhancement

#1047 Adding 4d support to statistics_base
  phylanx/plugins/statistics/statistics_base.hpp
  phylanx/plugins/statistics/statistics_base_impl.hpp
  tests/unit/plugins/statistics/all_operation.cpp
  tests/unit/plugins/statistics/sum_operation.cpp
Labels: category: primitives, submodule: backend

#1115 Remove left-over boolean that was enabling obsolete dtype handling for all generic primitives
  src/plugins/arithmetics/generic_operation.cpp
Labels: category: primitives, type: compatibility issue, type: enhancement

#1105 Fix #1104.
  python/phylanx/ast/physl.py
  python/src/bindings/execution_tree.cpp
  tests/regressions/python/1104_no_arg_lambda.py
  tests/regressions/python/CMakeLists.txt
Labels: compiler: python, submodule: frontend, type: defect
