Repository STEllAR-GROUP/phylanx, pull requests merged in 2020-05, with the labels that each got.

#1168 Adapting to recent HPX and blaze changes
  python/src/CMakeLists.txt
  src/plugins/keras_support/switch_operation.cpp
  tests/unit/algorithm/CMakeLists.txt
  tests/unit/plugins/controls/CMakeLists.txt
  tests/unit/plugins/controls/for_operation.cpp
Labels: category: CMake, type: compatibility issue, type: enhancement

#1165 Modifying shape and adding shape_d
  phylanx/plugins/matrixops/extract_shape.hpp
  src/plugins/matrixops/extract_shape.cpp
  src/plugins/matrixops/matrixops.cpp
  tests/unit/plugins/dist_matrixops/CMakeLists.txt
  tests/unit/plugins/dist_matrixops/dist_shape_2_loc.cpp
Labels: category: distributed, type: enhancement

#1166 Making expand_dims aware of annotations
  phylanx/plugins/matrixops/expand_dims.hpp
  src/plugins/matrixops/expand_dims.cpp
  tests/unit/plugins/dist_matrixops/CMakeLists.txt
  tests/unit/plugins/dist_matrixops/dist_expand_dims_2_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_expand_dims_3_loc.cpp
Labels: category: distributed, type: enhancement

#1156 Fixing annotation propagation problems
  phylanx/execution_tree/annotation.hpp
  phylanx/plugins/arithmetics/numeric_impl.hpp
  src/execution_tree/annotation.cpp
  src/plugins/arithmetics/add_operation.cpp
  src/plugins/arithmetics/generic_operation.cpp
  src/plugins/arithmetics/generic_operation_bool.cpp
  src/plugins/arithmetics/unary_minus_operation.cpp
  src/plugins/controls/async_operation.cpp
  src/plugins/keras_support/sigmoid_operation.cpp
  src/plugins/matrixops/gauss_inverse.cpp
  tests/regressions/CMakeLists.txt
  tests/regressions/distributed/1155_wrong_annotation_name.cpp
  tests/regressions/distributed/1155_wrong_broadcast.cpp
  tests/regressions/distributed/CMakeLists.txt
Labels: category: primitives, type: enhancement

#1164 Second attempt at allowing raw physl code to be passed to a Python
  python/phylanx/ast/physl.py
  python/phylanx/ast/transducer.py
  src/execution_tree/primitives/primitive_component.cpp
  tests/regressions/python/1170_no_error.py
  tests/regressions/python/CMakeLists.txt
Labels: category: @Phylanx, type: enhancement

#1158 Modify statistics given an empty list for axis
  phylanx/plugins/statistics/statistics_base.hpp
  phylanx/plugins/statistics/statistics_base_impl.hpp
  tests/unit/plugins/statistics/all_operation.cpp
  tests/unit/plugins/statistics/mean_operation.cpp
  tests/unit/plugins/statistics/min_operation.cpp
  tests/unit/plugins/statistics/std_operation.cpp
Labels: category: primitives, type: enhancement

#1161 Add primitive dist_diag.
  phylanx/plugins/dist_matrixops/dist_diag.hpp
  phylanx/plugins/dist_matrixops/dist_matrixops.hpp
  phylanx/plugins/dist_matrixops/idx_tile_calculation_helper.hpp
  phylanx/plugins/matrixops/diag_operation.hpp
  src/plugins/dist_matrixops/dist_diag.cpp
  src/plugins/dist_matrixops/dist_matrixops.cpp
  src/plugins/dist_matrixops/retile_annotations.cpp
  src/plugins/matrixops/diag_operation.cpp
  tests/unit/plugins/dist_matrixops/CMakeLists.txt
  tests/unit/plugins/dist_matrixops/dist_diag_2_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_diag_4_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_diag_6_loc.cpp
  tests/unit/plugins/matrixops/diag_operation.cpp
Labels: category: distributed, category: primitives

#1175 Making slice aware of annotations
  phylanx/execution_tree/primitives/slice_node_data.hpp
  phylanx/execution_tree/primitives/slice_node_data_2d.hpp
  phylanx/util/index_calculation_helper.hpp
  src/execution_tree/compiler/compiler.cpp
  src/execution_tree/localities_annotation.cpp
  src/execution_tree/primitives/slice.cpp
  src/execution_tree/primitives/slice_node_data.cpp
  src/plugins/dist_matrixops/dist_diag.cpp
  src/plugins/dist_matrixops/retile_annotations.cpp
  tests/unit/plugins/dist_matrixops/CMakeLists.txt
  tests/unit/plugins/dist_matrixops/dist_slice_2_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_slice_3_loc.cpp
Labels: category: distributed, type: enhancement

#1177 Distributed Inverse Operation
  phylanx/plugins/dist_matrixops/dist_inverse_operation.hpp
  phylanx/plugins/dist_matrixops/dist_matrixops.hpp
  src/plugins/dist_matrixops/dist_inverse_operation.cpp
  src/plugins/dist_matrixops/dist_matrixops.cpp
  tests/unit/plugins/dist_matrixops/CMakeLists.txt
  tests/unit/plugins/dist_matrixops/dist_inverse_2_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_inverse_3_loc.cpp
Labels: category: primitives, type: enhancement

#1181 Restricting annotate_d
  phylanx/execution_tree/meta_annotation.hpp
  phylanx/execution_tree/primitives/slice_node_data_2d.hpp
  phylanx/execution_tree/tiling_annotations.hpp
  src/execution_tree/localities_annotation.cpp
  src/execution_tree/locality_annotation.cpp
  src/execution_tree/meta_annotation.cpp
  src/execution_tree/primitives/annotate_primitive.cpp
  src/execution_tree/tiling_annotations.cpp
  tests/unit/execution_tree/annotation.cpp
  tests/unit/execution_tree/annotation_2_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_slice_2_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_slice_3_loc.cpp
Labels: category: distributed, type: enhancement
