Repository STEllAR-GROUP/phylanx, pull requests merged in 2020-06, with the labels that each got.

#1184 Fixing dangling reference in broadcasting vector->tensor
  src/execution_tree/primitives/node_data_helpers3d.cpp
  src/execution_tree/primitives/node_data_helpers4d.cpp
Labels: category: primitives, type: compatibility issue, type: enhancement

#1190 Give the option to physl to start a phylanx function at line one.
  python/phylanx/ast/transducer.py
Labels: category: @Phylanx, type: enhancement

#1185 Making sure duplicate variable/function names are properly diagnosed
  phylanx/ast/traverse.hpp
  phylanx/execution_tree/compiler/actors.hpp
  phylanx/execution_tree/compiler/compiler.hpp
  phylanx/execution_tree/compiler_component.hpp
  phylanx/execution_tree/primitives/primitive_argument_type.hpp
  phylanx/execution_tree/primitives/primitive_component.hpp
  phylanx/execution_tree/primitives/primitive_component_base.hpp
  phylanx/util/distributed_matrix.hpp
  phylanx/util/distributed_object.hpp
  phylanx/util/distributed_vector.hpp
  src/execution_tree/compiler/compiler.cpp
  src/execution_tree/primitives/base_primitive.cpp
  src/execution_tree/primitives/format_string.cpp
  src/execution_tree/primitives/primitive_component.cpp
  src/execution_tree/primitives/primitive_component_base.cpp
  src/plugins/controls/apply.cpp
  tests/regressions/execution_tree/out_of_scope_variable_232.cpp
  tests/unit/execution_tree/compiler.cpp
  tests/unit/execution_tree/compiler_component.cpp
  tests/unit/performance_counters/primitive_counter.cpp
  tests/unit/plugins/controls/parallel_map_operation.cpp
  tests/unit/plugins/matrixops/shuffle_operation.cpp
  tests/unit/python/execution_tree/for.py
Labels: category: PhySL, type: enhancement

#1191 Adapting Phylanx for recent changes in HPX collectives
  phylanx/plugins/dist_matrixops/dist_dot_operation_impl.hpp
  src/execution_tree/meta_annotation.cpp
  src/plugins/support_components.cpp
Labels: category: primitives, type: compatibility issue, type: enhancement

#1192 Adding 3d distributed random and constant
  phylanx/execution_tree/tiling_annotations.hpp
  phylanx/plugins/dist_matrixops/dist_constant.hpp
  phylanx/plugins/dist_matrixops/dist_random.hpp
  phylanx/plugins/dist_matrixops/tile_calculation_helper.hpp
  src/execution_tree/meta_annotation.cpp
  src/plugins/dist_matrixops/dist_constant.cpp
  src/plugins/dist_matrixops/dist_random.cpp
  src/plugins/dist_matrixops/dist_transpose_operation.cpp
  tests/unit/plugins/dist_matrixops/dist_constant_2_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_constant_3_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_constant_4_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_constant_6_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_random_2_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_random_4_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_random_5_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_transpose_operation.cpp
Labels: category: distributed, type: enhancement

#1199 Fixing inaccesible variables in slice operation used inside a store()
  src/execution_tree/primitives/access_argument.cpp
  src/ir/node_data.cpp
  tests/regressions/execution_tree/1198_inaccessible_variable.cpp
  tests/regressions/execution_tree/CMakeLists.txt
Labels: category: PhySL, category: primitives

#1201 Making sure not to reuse the names of built-in primitives
  examples/algorithms/als/als.cpp
  examples/algorithms/als/als_csv.cpp
  examples/algorithms/kmeans/kmeans.cpp
  examples/algorithms/kmeans/kmeans_fix_points.cpp
  examples/algorithms/kmeans/kmeans_fix_points_3d.cpp
  examples/algorithms/lra/lra.cpp
  examples/algorithms/lra/lra_csv.cpp
  examples/algorithms/lra/lra_csv_distributed.cpp
Labels: category: primitives, type: compatibility issue

#1202 Renaming gradient variable to prevent error as reported in #1200
  examples/algorithms/lra/lra.cpp
  examples/algorithms/lra/lra_csv.cpp
  examples/algorithms/lra/phylanx_lra_csv.py
  examples/algorithms/lra/phylanx_lra_csv_np.py
Labels: category: PhySL, type: compatibility issue, type: enhancement
