Repository STEllAR-GROUP/phylanx, pull requests merged in 2020-03, with the labels that each got.

#1116 Update copyright year in the Phylanx documentation
  cmake/templates/conf.py.in
Labels: category: documentation, type: enhancement

#1124 Adapting to changes in HighFive
  phylanx/util/detail/blaze-highfive.hpp
Labels: type: compatibility issue, type: enhancement

#1126 Adding distributed constant
  phylanx/execution_tree/primitives/base_primitive.hpp
  phylanx/execution_tree/tiling_annotations.hpp
  phylanx/plugins/common/constant_nd.hpp
  phylanx/plugins/dist_matrixops/dist_constant.hpp
  phylanx/plugins/dist_matrixops/dist_matrixops.hpp
  phylanx/plugins/matrixops/constant.hpp
  src/execution_tree/primitives/base_primitive.cpp
  src/plugins/common/constant_nd.cpp
  src/plugins/dist_matrixops/dist_constant.cpp
  src/plugins/dist_matrixops/dist_matrixops.cpp
  src/plugins/matrixops/constant.cpp
  tests/unit/plugins/dist_matrixops/CMakeLists.txt
  tests/unit/plugins/dist_matrixops/dist_constant_2_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_constant_4_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_constant_6_loc.cpp
  tests/unit/plugins/matrixops/constant.cpp
Labels: category: distributed, submodule: backend

#1127 Adding missing PHYLANX_COMMON_EXPORT
  phylanx/plugins/common/constant_nd.hpp
Labels: category: primitives, compiler: msvc, platform: Windows, type: enhancement

#1131 Fix macro processing issues
  python/src/init_hpx.cpp
  src/plugins/load_plugins.cpp
Labels: type: compatibility issue, type: enhancement

#1128 Making sure the full() primitive extracts default dtype from value argument
  phylanx/plugins/matrixops/constant.hpp
  python/phylanx/ast/physl.py
  src/plugins/matrixops/constant.cpp
  src/plugins/matrixops/matrixops.cpp
  tests/unit/python/execution_tree/primitives/numpy_dtype.py
Labels: category: PhySL, type: compatibility issue, type: enhancement

#1136 Remove CMake 3.11 installed as a temporary workaround
  tools/docker/base/Dockerfile
Labels: category: CMake, category: continuous integration

#1117 Distributing
  examples/algorithms/als/als.py
  phylanx/execution_tree/compiler_component.hpp
  phylanx/execution_tree/primitives.hpp
  phylanx/execution_tree/primitives/find_all_localities.hpp
  src/execution_tree/compiler_component.cpp
  src/execution_tree/patterns.cpp
  src/execution_tree/primitives/debug_output.cpp
  src/execution_tree/primitives/find_all_localities.cpp
  tests/unit/distributed/remote_run.cpp
Labels: category: distributed

#1140 Adapting to the recent changes in the HPX build system
  cmake/Phylanx_AddPrimitivePlugin.cmake
  examples/algorithms/als/CMakeLists.txt
  examples/algorithms/kmeans/CMakeLists.txt
  examples/algorithms/lir/CMakeLists.txt
  examples/algorithms/lra/CMakeLists.txt
  examples/algorithms/nn/CMakeLists.txt
  examples/ast/CMakeLists.txt
  examples/interpreter/CMakeLists.txt
  examples/profiling/CMakeLists.txt
  python/src/CMakeLists.txt
  src/CMakeLists.txt
  tests/regressions/execution_tree/CMakeLists.txt
  tests/unit/algorithm/CMakeLists.txt
  tests/unit/distributed/CMakeLists.txt
  tools/inspect/CMakeLists.txt
Labels: category: CMake, type: compatibility issue, type: enhancement

#1133 Make distributed span indices compatible with phylanx conventions
  phylanx/execution_tree/localities_annotation.hpp
  phylanx/execution_tree/tiling_annotations.hpp
  phylanx/plugins/dist_matrixops/dist_cannon_product_impl.hpp
  phylanx/plugins/dist_matrixops/dist_dot_operation_impl.hpp
  src/execution_tree/annotation.cpp
  src/execution_tree/localities_annotation.cpp
  src/execution_tree/tiling_annotations.cpp
  src/plugins/dist_matrixops/dist_constant.cpp
  src/plugins/dist_matrixops/dist_random.cpp
  tests/unit/execution_tree/CMakeLists.txt
  tests/unit/execution_tree/annotation.cpp
  tests/unit/execution_tree/annotation_2_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_constant_4_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_dot_operation.cpp
Labels: category: distributed, type: enhancement

#1135 Implementing async() primitive and related infrastructure
  phylanx/execution_tree/primitives/base_primitive.hpp
  phylanx/execution_tree/primitives/primitive_argument_type.hpp
  phylanx/plugins/booleans/comparison_impl.hpp
  phylanx/plugins/booleans/logical_operation_impl.hpp
  phylanx/plugins/controls/async_operation.hpp
  phylanx/plugins/controls/controls.hpp
  phylanx/util/variant.hpp
  python/src/bindings/binding_helpers.cpp
  python/src/bindings/execution_tree.cpp
  src/execution_tree/primitives/assert_condition.cpp
  src/execution_tree/primitives/base_primitive.cpp
  src/execution_tree/primitives/enable_tracing.cpp
  src/execution_tree/primitives/find_all_localities.cpp
  src/plugins/controls/async_operation.cpp
  src/plugins/controls/controls.cpp
  src/plugins/controls/filter_operation.cpp
  src/plugins/controls/if_conditional.cpp
  src/plugins/matrixops/random.cpp
  tests/unit/ast/node.cpp
  tests/unit/plugins/controls/CMakeLists.txt
  tests/unit/plugins/controls/async_operation.cpp
Labels: category: PhySL

#1142 Making sure random_d produces correctly sized 2d results
  phylanx/plugins/dist_matrixops/dist_constant.hpp
  phylanx/plugins/dist_matrixops/dist_random.hpp
  src/plugins/dist_matrixops/dist_constant.cpp
  src/plugins/dist_matrixops/dist_random.cpp
  tests/regressions/execution_tree/CMakeLists.txt
  tests/regressions/execution_tree/random_d_1139.cpp
Labels: category: primitives, type: compatibility issue, type: enhancement
