Repository STEllAR-GROUP/phylanx, pull requests merged in 2020-04, with the labels that each got.

#1143 Adding cannon product performance tests
  tests/performance/CMakeLists.txt
  tests/performance/dist_cannon.cpp
Labels: category: distributed, category: tests

#1123 add sequential gauss inverse plugin
  phylanx/plugins/matrixops/gauss_inverse.hpp
  phylanx/plugins/matrixops/matrixops.hpp
  src/plugins/matrixops/gauss_inverse.cpp
  src/plugins/matrixops/matrixops.cpp
  tests/unit/plugins/matrixops/CMakeLists.txt
  tests/unit/plugins/matrixops/gauss_inverse.cpp
Labels: category: primitives, type: enhancement

#1147 Modify random_d and constant_d to have tile_idx and numtiles as optional arguments
  phylanx/plugins/common/constant_nd.hpp
  phylanx/plugins/dist_matrixops/dist_random.hpp
  phylanx/plugins/dist_matrixops/tile_calculation_helper.hpp
  phylanx/plugins/matrixops/constant.hpp
  src/execution_tree/annotation.cpp
  src/plugins/common/constant_nd.cpp
  src/plugins/dist_matrixops/dist_constant.cpp
  src/plugins/dist_matrixops/dist_random.cpp
  src/plugins/matrixops/constant.cpp
  tests/unit/plugins/dist_matrixops/CMakeLists.txt
  tests/unit/plugins/dist_matrixops/dist_constant_2_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_constant_3_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_constant_4_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_constant_6_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_random_2_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_random_4_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_random_5_loc.cpp
Labels: category: distributed, type: enhancement

#1146 Add the dist_identity primitive
  phylanx/plugins/dist_matrixops/dist_identity.hpp
  phylanx/plugins/dist_matrixops/dist_matrixops.hpp
  src/plugins/dist_matrixops/dist_identity.cpp
  src/plugins/dist_matrixops/dist_matrixops.cpp
  tests/unit/plugins/dist_matrixops/CMakeLists.txt
  tests/unit/plugins/dist_matrixops/dist_identity_2_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_identity_4_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_identity_6_loc.cpp
Labels: category: distributed, category: primitives

#1148 Modifying dist_matrix fetch function and cannon_product name
  phylanx/plugins/dist_matrixops/dist_cannon_product.hpp
  phylanx/plugins/dist_matrixops/dist_cannon_product_impl.hpp
  phylanx/plugins/dist_matrixops/dist_dot_operation_impl.hpp
  phylanx/plugins/dist_matrixops/tile_calculation_helper.hpp
  phylanx/util/distributed_matrix.hpp
  src/plugins/dist_matrixops/dist_cannon_product.cpp
  tests/performance/dist_cannon.cpp
  tests/unit/plugins/dist_matrixops/CMakeLists.txt
  tests/unit/plugins/dist_matrixops/dist_cannon_product_4_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_cannon_product_9_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_dot_operation_2_loc.cpp
Labels: category: distributed, type: enhancement

#1149 Adding Retile for distributed arrays
  phylanx/plugins/dist_matrixops/dist_matrixops.hpp
  phylanx/plugins/dist_matrixops/retile_annotations.hpp
  phylanx/plugins/dist_matrixops/tile_calculation_helper.hpp
  phylanx/util/detail/range_dimension.hpp
  src/plugins/dist_matrixops/dist_constant.cpp
  src/plugins/dist_matrixops/dist_matrixops.cpp
  src/plugins/dist_matrixops/dist_random.cpp
  src/plugins/dist_matrixops/retile_annotations.cpp
  src/plugins/matrixops/constant.cpp
  tests/unit/plugins/dist_matrixops/CMakeLists.txt
  tests/unit/plugins/dist_matrixops/retile_2_loc.cpp
  tests/unit/plugins/dist_matrixops/retile_3_loc.cpp
  tests/unit/plugins/dist_matrixops/retile_6_loc.cpp
Labels: category: distributed

#1154 Printing out seed in case of error in remote_add test
  tests/unit/distributed/remote_add.cpp
Labels: category: tests, type: enhancement
