Repository STEllAR-GROUP/phylanx, pull requests merged in 2020-07, with the labels that each got.

#1205 Adding distributed conv1d
  .circleci/config.yml
  examples/algorithms/kmeans/kmeans_fix_points.cpp
  examples/algorithms/kmeans/kmeans_fix_points_3d.cpp
  phylanx/execution_tree/localities_annotation.hpp
  phylanx/include/plugins.hpp
  phylanx/plugins/common/conv1d_all_paddings.hpp
  phylanx/plugins/dist_keras_support/dist_conv1d.hpp
  phylanx/plugins/dist_keras_support/dist_keras_support.hpp
  phylanx/plugins/dist_matrixops/dist_argminmax_impl.hpp
  phylanx/plugins/keras_support/conv1d_operation.hpp
  phylanx/plugins/keras_support/conv_indices_helper.hpp
  src/execution_tree/localities_annotation.cpp
  src/plugins/CMakeLists.txt
  src/plugins/common/conv1d_all_paddings.cpp
  src/plugins/dist_keras_support/CMakeLists.txt
  src/plugins/dist_keras_support/dist_conv1d.cpp
  src/plugins/dist_keras_support/dist_keras_support.cpp
  src/plugins/keras_support/CMakeLists.txt
  src/plugins/keras_support/conv1d_operation.cpp
  tests/unit/plugins/CMakeLists.txt
  tests/unit/plugins/dist_keras_support/CMakeLists.txt
  tests/unit/plugins/dist_keras_support/dist_conv1d_2_loc.cpp
  tests/unit/plugins/dist_keras_support/dist_conv1d_3_loc.cpp
  tests/unit/plugins/dist_keras_support/dist_conv1d_4_loc.cpp
Labels: category: distributed, category: primitives, submodule: backend

#1207 Use shared_ptr to an array only if it's supported
  CMakeLists.txt
  cmake/Phylanx_AddConfigTests.cmake
  cmake/Phylanx_PerformCxxFeatureTests.cmake
  cmake/tests/cxx17_shared_ptr_array.cpp
  phylanx/execution_tree/compiler/actors.hpp
  src/execution_tree/compiler/compiler.cpp
Labels: category: CMake, type: compatibility issue, type: enhancement

#1212 Moving mod_operation to arithmetics plugin
  phylanx/execution_tree/primitives.hpp
  phylanx/plugins/arithmetics/arithmetics.hpp
  phylanx/plugins/arithmetics/mod_operation.hpp
  phylanx/util/distributed_matrix.hpp
  phylanx/util/distributed_object.hpp
  phylanx/util/distributed_tensor.hpp
  phylanx/util/distributed_vector.hpp
  src/execution_tree/patterns.cpp
  src/plugins/arithmetics/arithmetics.cpp
  src/plugins/arithmetics/mod_operation.cpp
Labels: category: primitives

#1215 Add functions for slicing distributed arrays locally
  phylanx/execution_tree/primitives/slice.hpp
  phylanx/execution_tree/primitives/slice_node_data.hpp
  phylanx/execution_tree/primitives/slice_node_data_2d.hpp
  phylanx/plugins/matrixops/slicing_operation.hpp
  src/execution_tree/compiler/compiler.cpp
  src/execution_tree/primitives/slice.cpp
  src/execution_tree/primitives/slice_node_data.cpp
  src/plugins/matrixops/matrixops.cpp
  src/plugins/matrixops/slicing_operation.cpp
  tests/unit/plugins/dist_matrixops/dist_slice_2_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_slice_3_loc.cpp
Labels: category: algorithms, category: distributed, category: examples

#1209 Adding distributed file_read_csv
  phylanx/plugins/dist_matrixops/dist_constant.hpp
  phylanx/plugins/dist_matrixops/tile_calculation_helper.hpp
  phylanx/plugins/fileio/dist_file_read_csv.hpp
  phylanx/plugins/fileio/file_read_csv.hpp
  phylanx/plugins/fileio/file_read_csv_impl.hpp
  phylanx/plugins/fileio/fileio.hpp
  src/plugins/dist_matrixops/dist_constant.cpp
  src/plugins/dist_matrixops/retile_annotations.cpp
  src/plugins/fileio/CMakeLists.txt
  src/plugins/fileio/dist_file_read_csv.cpp
  src/plugins/fileio/file_read_csv.cpp
  src/plugins/fileio/fileio.cpp
  tests/unit/plugins/dist_matrixops/dist_constant_2_loc.cpp
  tests/unit/plugins/dist_matrixops/dist_constant_6_loc.cpp
  tests/unit/plugins/dist_matrixops/retile_3_loc.cpp
  tests/unit/plugins/dist_matrixops/retile_6_loc.cpp
  tests/unit/plugins/fileio/CMakeLists.txt
  tests/unit/plugins/fileio/dist_read_csv_2_loc.cpp
Labels: category: distributed, category: primitives, submodule: backend, type: enhancement
