Repository STEllAR-GROUP/phylanx, pull requests merged in 2021-01, with the labels that each got.

#1298 Address the removal of Python 2 from CI image
  .circleci/config.yml
  tools/circleci/check_test_coverage.py
  tools/flake8/flake_to_junit.py
  tools/inspect/inspect_to_junit.py
Labels: category: CMake, type: compatibility issue, type: enhancement

#1308 Enable iterating over arrays (scalars, vectors, matrices)
  phylanx/plugins/controls/for_each.hpp
  src/plugins/controls/for_each.cpp
  tests/regressions/python/1303_iterate_over_array.py
  tests/regressions/python/CMakeLists.txt
Labels: category: primitives, type: compatibility issue, type: enhancement

#1305 Fixing stack operations to accept lists
  src/plugins/matrixops/stack_operation.cpp
  tests/regressions/python/1302_array.py
  tests/regressions/python/CMakeLists.txt
Labels: category: primitives, type: compatibility issue, type: enhancement

#1309 Allowing double-indexing of 1D arrays
  src/execution_tree/primitives/slice_node_data.cpp
  tests/regressions/python/1306_indexing.py
  tests/regressions/python/CMakeLists.txt
Labels: category: primitives, type: compatibility issue, type: enhancement

#1310 Making sure that debug=True prints generated PhySL at function definition
  python/phylanx/ast/physl.py
Labels: category: @Phylanx, type: enhancement
